// GENERISANO — ne menjati rukom. Pravi ga `node scripts/snimi-izgovor.mjs`.
//
// Šta ima snimljen izgovor (glas Montse, katalonski).
// Aplikacija prvo traži snimak; ako ga nema, čita glasom uređaja kao i pre —
// zato dodavanje nove reči ništa ne kvari, samo joj fali snimak dok se skripta
// ne pusti ponovo.
export const SNIMLJENO: Record<string, string> = {
  "llapis": "llapis",
  "goma": "goma",
  "bolígraf": "boligraf-a401bd",
  "retolador": "retolador",
  "llibreta": "llibreta",
  "llibre": "llibre",
  "carpeta": "carpeta",
  "estoig": "estoig",
  "maquineta": "maquineta",
  "regle": "regle",
  "motxilla": "motxilla",
  "tisores": "tisores",
  "pissarra": "pissarra",
  "guix": "guix",
  "esborrador": "esborrador",
  "paperera": "paperera",
  "ordinador": "ordinador",
  "taula": "taula",
  "cadira": "cadira",
  "porta": "porta",
  "finestra": "finestra",
  "blava": "blava",
  "groc": "groc",
  "vermell": "vermell",
  "taronja": "taronja",
  "gris": "gris",
  "lila": "lila",
  "negres": "negres",
  "retallar": "retallar",
  "escriure": "escriure",
  "cola de barra": "cola-de-barra",
  "enganxar": "enganxar",
  "llapis de colors": "llapis-de-colors",
  "pintar": "pintar",
  "esborrar": "esborrar",
  "dibuixa": "dibuixa",
  "pinta": "pinta",
  "canta": "canta",
  "escriu": "escriu",
  "retalla": "retalla",
  "retoladors": "retoladors",
  "lla": "lla",
  "pis": "pis",
  "ti": "ti",
  "sores": "sores",
  "ca": "ca",
  "dira": "dira",
  "mot": "mot",
  "xilla": "xilla",
  "fi": "fi",
  "nestra": "nestra",
  "lli": "lli",
  "bre": "bre",
  "pinta el llapis de color blau": "pinta-el-llapis-de-color-bla-833ec6",
  "pinta la goma de color verd": "pinta-la-goma-de-color-verd",
  "pinta l'ordinador de color negre": "pinta-l-ordinador-de-color-n-70d94f",
  "pinta les tisores de color vermell": "pinta-les-tisores-de-color-v-59996f",
  "pinta la maquineta de color groc": "pinta-la-maquineta-de-color--0398c0",
  "pinta el llibre de color blanc": "pinta-el-llibre-de-color-bla-bdf3cf",
  "pinta la motxilla de color lila": "pinta-la-motxilla-de-color-l-cad099",
  "pinta l'estoig de color verd": "pinta-l-estoig-de-color-verd",
  "pinta el regle de color taronja": "pinta-el-regle-de-color-taro-af24c2",
  "pinta el retolador de color marró": "pinta-el-retolador-de-color--760d3a",
  "pinta la carpeta de color rosa": "pinta-la-carpeta-de-color-ro-47d6c3",
  "pinta la pissarra de color verd": "pinta-la-pissarra-de-color-v-769465",
  "la maquineta és": "la-maquineta-es-46970c",
  "el regle és": "el-regle-es-39711c",
  "el bolígraf és": "el-boligraf-es-321af6",
  "el pinzell és": "el-pinzell-es-8b6154",
  "el clip és": "el-clip-es-291579",
  "la cola de barra és": "la-cola-de-barra-es-aab5ef",
  "les tisores són": "les-tisores-son-86607a",
  "l'ema": "l-ema",
  "en pau": "en-pau",
  "la júlia": "la-julia-40a342",
  "en hugo": "en-hugo",
  "la mia": "la-mia",
  "jo retallo amb les": "jo-retallo-amb-les",
  "jo escric amb el": "jo-escric-amb-el",
  "jo esborro amb la": "jo-esborro-amb-la",
  "jo dibuixo amb els": "jo-dibuixo-amb-els",
  "nosaltres dibuixem a la": "nosaltres-dibuixem-a-la",
  "llegeix i copia les paraules de la classe (1 de 3).": "llegeix-i-copia-les-paraules-af1985",
  "busca 10 paraules a la sopa de lletres. poden anar": "busca-10-paraules-a-la-sopa--e7e2e4",
  "llegeix i copia les paraules de la classe (2 de 3).": "llegeix-i-copia-les-paraules-4efb30",
  "completa la paraula (1 de 3).": "completa-la-paraula-1-de-3",
  "llegeix i copia les paraules de la classe (3 de 3).": "llegeix-i-copia-les-paraules-077f45",
  "completa la paraula (2 de 3).": "completa-la-paraula-2-de-3",
  "classifica les paraules: femení (una) o masculí (un).": "classifica-les-paraules-feme-fd275b",
  "completa la paraula (3 de 3).": "completa-la-paraula-3-de-3",
  "relaciona cada dibuix amb la seva paraula.": "relaciona-cada-dibuix-amb-la-4cc2d4",
  "classifica les paraules: un (singular) o molts (plural).": "classifica-les-paraules-un-s-89d761",
  "pinta cada objecte del color indicat.": "pinta-cada-objecte-del-color-9de476",
  "observa l'estoig i completa les frases.": "observa-l-estoig-i-completa--1cb27a",
  "relaciona cada objecte amb la seva funció.": "relaciona-cada-objecte-amb-l-a5f676",
  "què fan? completa les frases.": "que-fan-completa-les-frases-0f9b2e",
  "classifica: quines paraules són objectes de classe?": "classifica-quines-paraules-s-649146",
  "afegeix l'article: el, la o l'.": "afegeix-l-article-el-la-o-l",
  "escriu el nom dels mobles de la classe.": "escriu-el-nom-dels-mobles-de-7cbd4e",
  "completa les frases.": "completa-les-frases",
  "separa les paraules i copia la frase.": "separa-les-paraules-i-copia--27e3d1",
  "autoavaluació: revisa el vocabulari de la classe.": "autoavaluacio-revisa-el-voca-e3f9f1",
  "relaciona les dues parts per formar paraules:": "relaciona-les-dues-parts-per-67dfa5",
  "activitat extra! diverteix-te, activa la creativitat i dibuixa alguna cosa màgica!": "activitat-extra-diverteix-te-5dfc66",
  "bolígrafs": "boligrafs-b62f6e",
  "llibretes": "llibretes",
  "carpetes": "carpetes",
  "maquinetes": "maquinetes",
  "motxilles": "motxilles",
  "vermella": "vermella",
  "groga": "groga",
  "blau": "blau",
  "negre": "negre",
  "verd": "verd",
  "blanc": "blanc",
  "verda": "verda",
  "grises": "grises",
  "blanques": "blanques",
  "cuina": "cuina",
  "pare": "pare",
  "gat": "gat",
  "televisió": "televisio-dbd5ce",
  "anell": "anell",
  "bicicleta": "bicicleta",
  "collaret": "collaret",
  "gomes": "gomes",
  "regles": "regles",
  "llibres": "llibres",
  "guixos": "guixos",
  "els": "els",
  "nens": "nens",
  "escriuen": "escriuen",
  "a": "a",
  "la": "la",
  "el": "el",
  "és": "es-277e59",
  "de": "de",
  "color": "color",
  "la maquineta": "la-maquineta",
  "la goma": "la-goma",
  "el llapis": "el-llapis",
  "la llibreta": "la-llibreta",
  "el guix": "el-guix",
  "la carpeta": "la-carpeta",
  "l' ordinador": "l-ordinador",
  "el retolador": "el-retolador",
  "tisores, retallar": "tisores-retallar",
  "llapis, escriure": "llapis-escriure",
  "cola de barra, enganxar": "cola-de-barra-enganxar",
  "llapis de colors, pintar": "llapis-de-colors-pintar",
  "goma, esborrar": "goma-esborrar",
  "una goma": "una-goma",
  "una llibreta": "una-llibreta",
  "una carpeta": "una-carpeta",
  "una maquineta": "una-maquineta",
  "una motxilla": "una-motxilla",
  "una tisores": "una-tisores",
  "un llapis": "un-llapis",
  "un bolígraf": "un-boligraf-2b3049",
  "un retolador": "un-retolador",
  "un llibre": "un-llibre",
  "un estoig": "un-estoig",
  "un regle": "un-regle",
  "un goma": "un-goma",
  "molts bolígrafs": "molts-boligrafs-00e1da",
  "molts retoladors": "molts-retoladors",
  "molts llibretes": "molts-llibretes",
  "molts carpetes": "molts-carpetes",
  "molts maquinetes": "molts-maquinetes",
  "molts motxilles": "molts-motxilles",
  "molts tisores": "molts-tisores",
  "aula": "aula",
  "biblioteca": "biblioteca",
  "laboratori": "laboratori",
  "passadís": "passadis-e75e0d",
  "lavabo": "lavabo",
  "menjador": "menjador",
  "gimnàs": "gimnas-d2a285",
  "pati": "pati",
  "classe": "classe",
  "matemàtiques": "matematiques-04d055",
  "llengües": "llengues-d23822",
  "música": "musica-56a08b",
  "ciències": "ciencies-cb9177",
  "anglès": "angles-833cc8",
  "informàtica": "informatica-d1db31",
  "educació física": "educacio-fisica-ff42c7",
  "plàstica": "plastica-65db90",
  "onze": "onze",
  "dotze": "dotze",
  "tretze": "tretze",
  "catorze": "catorze",
  "quinze": "quinze",
  "setze": "setze",
  "disset": "disset",
  "divuit": "divuit",
  "dinou": "dinou",
  "vint": "vint",
  "la classe": "la-classe",
  "les classes": "les-classes",
  "el pati": "el-pati",
  "els patis": "els-patis",
  "la noia": "la-noia",
  "les noies": "les-noies",
  "el noi": "el-noi",
  "els nois": "els-nois",
  "l'escola": "l-escola",
  "les escoles": "les-escoles",
  "la biblioteca": "la-biblioteca",
  "les biblioteques": "les-biblioteques",
  "el lavabo": "el-lavabo",
  "els lavabos": "els-lavabos",
  "el passadís": "el-passadis-595c79",
  "els passadissos": "els-passadissos",
  "dilluns": "dilluns",
  "dimarts": "dimarts",
  "dimecres": "dimecres",
  "dijous": "dijous",
  "divendres": "divendres",
  "dissabte": "dissabte",
  "diumenge": "diumenge",
  "a sobre": "a-sobre",
  "a sota": "a-sota",
  "a dins": "a-dins",
  "a fora": "a-fora",
  "al costat": "al-costat",
  "al davant": "al-davant",
  "al darrere": "al-darrere",
  "entres": "entres",
  "entra": "entra",
  "entrem": "entrem",
  "entren": "entren",
  "surts": "surts",
  "surt": "surt",
  "sortim": "sortim",
  "surten": "surten",
  "pa": "pa",
  "gim": "gim",
  "nàs": "nas-b76974",
  "vabo": "vabo",
  "men": "men",
  "jador": "jador",
  "bi": "bi",
  "blioteca": "blioteca",
  "labo": "labo",
  "ratori": "ratori",
  "el és el cinquè dia de la setmana.": "el-es-el-cinque-dia-de-la-se-2112d5",
  "el és el primer dia de la setmana.": "el-es-el-primer-dia-de-la-se-a3db43",
  "el és el setè dia de la setmana.": "el-es-el-sete-dia-de-la-setm-410050",
  "el és el tercer dia de la setmana.": "el-es-el-tercer-dia-de-la-se-674d24",
  "el és el sisè dia de la setmana.": "el-es-el-sise-dia-de-la-setm-268d09",
  "el és el segon dia de la setmana.": "el-es-el-segon-dia-de-la-set-959514",
  "el és el quart dia de la setmana.": "el-es-el-quart-dia-de-la-set-a13ce9",
  "el dia abans de divendres és": "el-dia-abans-de-divendres-es-455658",
  "el dia després de divendres és": "el-dia-despres-de-divendres--7cfaaa",
  "el dia abans de dimarts és": "el-dia-abans-de-dimarts-es-df0d92",
  "el dia després de dimarts és": "el-dia-despres-de-dimarts-es-b3a4f9",
  "el dia abans de diumenge és": "el-dia-abans-de-diumenge-es-046762",
  "el dia després de diumenge és": "el-dia-despres-de-diumenge-e-ed0503",
  "el dia abans de dijous és": "el-dia-abans-de-dijous-es-4037d6",
  "el dia després de dijous és": "el-dia-despres-de-dijous-es-ddd859",
  "el gat està la cadira.": "el-gat-esta-la-cadira-79af79",
  "el gat està de la caixa.": "el-gat-esta-de-la-caixa-467688",
  "el gat està de la cadira.": "el-gat-esta-de-la-cadira-d5dce0",
  "jo entro al menjador. tu al menjador.": "jo-entro-al-menjador-tu-al-m-92e39f",
  "jo entro al menjador. ell al menjador.": "jo-entro-al-menjador-ell-al--beee23",
  "jo entro al menjador. nosaltres al menjador.": "jo-entro-al-menjador-nosaltr-672301",
  "jo entro al menjador. ells al menjador.": "jo-entro-al-menjador-ells-al-165bc4",
  "jo surto al passadís. tu al passadís.": "jo-surto-al-passadis-tu-al-p-418adc",
  "jo surto al passadís. ell al passadís.": "jo-surto-al-passadis-ell-al--88c9f8",
  "jo surto al passadís. nosaltres al passadís.": "jo-surto-al-passadis-nosaltr-91c175",
  "jo surto al passadís. ells al passadís.": "jo-surto-al-passadis-ells-al-2e9b5d",
  "llegeix i copia les paraules:": "llegeix-i-copia-les-paraules",
  "completa amb les lletres que falten:": "completa-amb-les-lletres-que-dbed17",
  "escriu l'article correcte: el o la?": "escriu-l-article-correcte-el-857334",
  "ordena les síl·labes i escriu la paraula:": "ordena-les-sil-labes-i-escri-aa0f1d",
  "observa i copia les assignatures:": "observa-i-copia-les-assignat-9924b3",
  "escriu el nom de les assignatures sense mirar!": "escriu-el-nom-de-les-assigna-ef4ba4",
  "observa i escriu els números de l'11 al 20:": "observa-i-escriu-els-numeros-14b33d",
  "encercla les paraules relacionades amb l'escola:": "encercla-les-paraules-relaci-885003",
  "relaciona el singular amb el plural:": "relaciona-el-singular-amb-el-d7b527",
  "llegeix i copia els dies de la setmana:": "llegeix-i-copia-els-dies-de--72c84f",
  "completa els dies de la setmana:": "completa-els-dies-de-la-setm-802237",
  "completa les lletres que falten dels dies:": "completa-les-lletres-que-fal-52506d",
  "escriu el dia d'abans i el de després:": "escriu-el-dia-d-abans-i-el-d-9c34df",
  "on és el gat? observa i copia les preposicions de lloc:": "on-es-el-gat-observa-i-copia-2264ba",
  "on és el gat? completa amb la preposició correcta:": "on-es-el-gat-completa-amb-la-c945e8",
  "saps dir aquestes paraules en català?": "saps-dir-aquestes-paraules-e-85ffbc",
  "completa les frases amb el verb correcte:": "completa-les-frases-amb-el-v-1e27c6",
  "platja": "platja",
  "muntanya": "muntanya",
  "bosc": "bosc",
  "mercat": "mercat",
  "cinema": "cinema",
  "parc": "parc",
  "entreu": "entreu",
  "sortiu": "sortiu",
  "el laboratori": "el-laboratori",
  "el menjador": "el-menjador",
  "el gimnàs": "el-gimnas-247e78",
  "la classe, les classes": "la-classe-les-classes",
  "el pati, els patis": "el-pati-els-patis",
  "la noia, les noies": "la-noia-les-noies",
  "el noi, els nois": "el-noi-els-nois",
  "l'escola, les escoles": "l-escola-les-escoles",
  "la biblioteca, les biblioteques": "la-biblioteca-les-bibliotequ-ccced9",
  "el lavabo, els lavabos": "el-lavabo-els-lavabos",
  "el passadís, els passadissos": "el-passadis-els-passadissos-6d54d9",
  "boca": "boca",
  "ull": "ull",
  "nas": "nas",
  "dents": "dents",
  "cabell": "cabell",
  "orella": "orella",
  "braç": "brac-c0e95b",
  "cama": "cama",
  "cara": "cara",
  "colze": "colze",
  "panxa": "panxa",
  "ungla": "ungla",
  "mà": "ma-7c0a70",
  "dit": "dit",
  "peu": "peu",
  "veure": "veure",
  "escoltar": "escoltar",
  "olorar": "olorar",
  "parlar": "parlar",
  "tocar": "tocar",
  "mirar": "mirar",
  "cantar": "cantar",
  "aplaudir": "aplaudir",
  "mirem": "mirem",
  "ulls": "ulls",
  "escoltem": "escoltem",
  "orelles": "orelles",
  "parlem": "parlem",
  "aplaudim": "aplaudim",
  "mans": "mans",
  "caminem": "caminem",
  "cames": "cames",
  "jove": "jove",
  "vell": "vell",
  "alt": "alt",
  "baix": "baix",
  "alta": "alta",
  "vella": "vella",
  "baixa": "baixa",
  "sara": "sara",
  "xavier": "xavier",
  "carolina": "carolina",
  "sergi": "sergi",
  "bell": "bell",
  "o": "o",
  "rella": "rella",
  "pan": "pan",
  "xa": "xa",
  "col": "col",
  "ze": "ze",
  "ge": "ge",
  "noll": "noll",
  "un": "un",
  "gla": "gla",
  "la laura és més que en carles.": "la-laura-es-mes-que-en-carle-c6f32e",
  "en carles és més que la laura.": "en-carles-es-mes-que-la-laur-70fdad",
  "la maria té els ulls grans?": "la-maria-te-els-ulls-grans-26fd03",
  "els seus ulls són verds?": "els-seus-ulls-son-verds-8b0908",
  "té un nas petit?": "te-un-nas-petit-c0afe9",
  "és una persona jove?": "es-una-persona-jove-08e48c",
  "té el cabell negre?": "te-el-cabell-negre-66ada7",
  "se li veuen les dents?": "se-li-veuen-les-dents",
  "el cabell li tapa una orella?": "el-cabell-li-tapa-una-orella",
  "es diu maria?": "es-diu-maria",
  "un noi vell una noia": "un-noi-vell-una-noia",
  "un noi alt una noia": "un-noi-alt-una-noia",
  "un noi baix una noia": "un-noi-baix-una-noia",
  "un noi jove una noia": "un-noi-jove-una-noia",
  "bigoti": "bigoti",
  "barba": "barba",
  "ulleres": "ulleres",
  "la és molt jove, amb el cabell marró recollit en una cua.": "la-es-molt-jove-amb-el-cabel-2f9b1f",
  "en és jove i alt, té bigoti i el cabell curt.": "en-es-jove-i-alt-te-bigoti-i-3420dc",
  "la és jove, té el cabell llarg i negre. també porta ulleres.": "la-es-jove-te-el-cabell-llar-0111af",
  "en és un nen baix, amb el cabell curt i negre.": "en-es-un-nen-baix-amb-el-cab-76e151",
  "llegeix i copia les parts del cos (1 de 3).": "llegeix-i-copia-les-parts-de-4d78dd",
  "escriu les parts del cap.": "escriu-les-parts-del-cap",
  "llegeix i copia les parts del cos (2 de 3).": "llegeix-i-copia-les-parts-de-78d60e",
  "ordena les síl·labes per formar paraules.": "ordena-les-sil-labes-per-for-9ad7ab",
  "llegeix i copia les parts del cos (3 de 3).": "llegeix-i-copia-les-parts-de-e9cb94",
  "busca 7 paraules a la sopa de lletres. poden anar": "busca-7-paraules-a-la-sopa-d-af18c8",
  "classifica: és una part del cap o del cos?": "classifica-es-una-part-del-c-80d754",
  "uneix cada part del cos amb la seva funció.": "uneix-cada-part-del-cos-amb--02088a",
  "observa i busca les paraules a la sopa de lletres. poden anar": "observa-i-busca-les-paraules-704662",
  "llegeix i copia els verbs dels sentits.": "llegeix-i-copia-els-verbs-de-2f0ec5",
  "relaciona cada acció amb la part del cos.": "relaciona-cada-accio-amb-la--c75300",
  "observa i copia les paraules noves:": "observa-i-copia-les-paraules-fee4a9",
  "observa i completa les frases.": "observa-i-completa-les-frase-232b7d",
  "observa la maria i contesta sí o no.": "observa-la-maria-i-contesta--47fe61",
  "fixa-t'hi i completa: noi noia.": "fixa-t-hi-i-completa-noi-noi-634893",
  "observa el vocabulari nou i completa les parts que falten.": "observa-el-vocabulari-nou-i--8057ab",
  "qui és qui? llegeix i escriu el nom correcte.": "qui-es-qui-llegeix-i-escriu--4f5bc8",
  "autoavaluació: les parts del cos.": "autoavaluacio-les-parts-del--731853",
  "cap": "cap",
  "sí": "si-873caa",
  "no": "no",
  "ull, veure": "ull-veure",
  "orella, escoltar": "orella-escoltar",
  "nas, olorar": "nas-olorar",
  "boca, parlar": "boca-parlar",
  "mà, tocar": "ma-tocar-7d6260",
  "mirem, ulls": "mirem-ulls",
  "escoltem, orelles": "escoltem-orelles",
  "parlem, boca": "parlem-boca",
  "aplaudim, mans": "aplaudim-mans",
  "caminem, cames": "caminem-cames",
  "genoll": "genoll",
  "anorac": "anorac",
  "jersei": "jersei",
  "texans": "texans",
  "pantalons": "pantalons",
  "samarreta": "samarreta",
  "camisa": "camisa",
  "jaqueta": "jaqueta",
  "faldilla": "faldilla",
  "vestit": "vestit",
  "xandall": "xandall",
  "americana": "americana",
  "abric": "abric",
  "cinturó": "cinturo-d85c7f",
  "corbata": "corbata",
  "gorro": "gorro",
  "pantalons curts": "pantalons-curts",
  "botes": "botes",
  "mitjons": "mitjons",
  "sabates": "sabates",
  "gorra": "gorra",
  "vambes": "vambes",
  "guants": "guants",
  "bufanda": "bufanda",
  "barret": "barret",
  "banyador": "banyador",
  "biquini": "biquini",
  "banyador de dona": "banyador-de-dona",
  "pijama": "pijama",
  "calçotets": "calcotets-97170d",
  "calces": "calces",
  "calçotet": "calcotet-daa057",
  "bota": "bota",
  "bruts": "bruts",
  "nou": "nou",
  "velles": "velles",
  "nets": "nets",
  "arracades": "arracades",
  "rellotge": "rellotge",
  "sandàlies": "sandalies-280384",
  "nell": "nell",
  "sandà": "sanda-a63697",
  "lies": "lies",
  "rello": "rello",
  "tge": "tge",
  "mit": "mit",
  "jons": "jons",
  "co": "co",
  "llaret": "llaret",
  "ves": "ves",
  "tit": "tit",
  "els pantalons estan": "els-pantalons-estan",
  "el jersei és": "el-jersei-es-59b746",
  "les sabates són": "les-sabates-son-222024",
  "els mitjons estan": "els-mitjons-estan",
  "pinta el jersei de blau": "pinta-el-jersei-de-blau",
  "pinta les botes de marró": "pinta-les-botes-de-marro-511aab",
  "pinta els mitjons de verd": "pinta-els-mitjons-de-verd",
  "pinta el pijama de lila": "pinta-el-pijama-de-lila",
  "pinta els guants de rosa": "pinta-els-guants-de-rosa",
  "les portem als peus:": "les-portem-als-peus",
  "ens abriga a l'hivern:": "ens-abriga-a-l-hivern",
  "ens la posem al cap:": "ens-la-posem-al-cap",
  "té botons:": "te-botons-e24348",
  "ens abriga les mans:": "ens-abriga-les-mans",
  "ens els posem als peus i no són sabates:": "ens-els-posem-als-peus-i-no--09be15",
  "ens el posem per dormir:": "ens-el-posem-per-dormir",
  "el portem per anar a la piscina:": "el-portem-per-anar-a-la-pisc-7cfdf9",
  "el portem per fer exercici:": "el-portem-per-fer-exercici",
  "llegeix i copia les peces de roba: (1 de 3).": "llegeix-i-copia-les-peces-de-a2fe07",
  "observa i escriu les peces de roba.": "observa-i-escriu-les-peces-d-07486d",
  "llegeix i copia les peces de roba: (2 de 3).": "llegeix-i-copia-les-peces-de-559f97",
  "llegeix i copia les peces de roba: (3 de 3).": "llegeix-i-copia-les-peces-de-2c42a6",
  "busca 6 peces de vestir a la sopa de lletres. poden anar": "busca-6-peces-de-vestir-a-la-577b1c",
  "encercla les peces de vestir:": "encercla-les-peces-de-vestir",
  "escriu l'article correcte: un o una?": "escriu-l-article-correcte-un-bcb769",
  "observa i completa les frases:": "observa-i-completa-les-frase-ce5e9e",
  "llegeix i copia els complements:": "llegeix-i-copia-els-compleme-e81d8f",
  "llegeix i pinta la roba:": "llegeix-i-pinta-la-roba",
  "escriu cada paraula al seu lloc:": "escriu-cada-paraula-al-seu-l-978c17",
  "nous": "nous",
  "brut": "brut",
  "noves": "noves",
  "netes": "netes",
  "vells": "vells",
  "un abric": "un-abric",
  "una camisa": "una-camisa",
  "un jersei": "un-jersei",
  "una gorra": "una-gorra",
  "una faldilla": "una-faldilla",
  "un calçotet": "un-calcotet-db3d62",
  "una jaqueta": "una-jaqueta",
  "una corbata": "una-corbata",
  "un pijama": "un-pijama",
  "una bota": "una-bota",
  "a, nell": "a-nell",
  "sandà, lies": "sanda-lies-3848b2",
  "rello, tge": "rello-tge",
  "mit, jons": "mit-jons",
  "co, llaret": "co-llaret",
  "ves, tit": "ves-tit",
  "teulada": "teulada",
  "xemeneia": "xemeneia",
  "antena": "antena",
  "balcó": "balco-1d8638",
  "persiana": "persiana",
  "cortina": "cortina",
  "escala": "escala",
  "jardí": "jardi-217bbb",
  "garatge": "garatge",
  "per protegir de la pluja": "per-protegir-de-la-pluja",
  "per pujar al pis de dalt": "per-pujar-al-pis-de-dalt",
  "per veure la televisió": "per-veure-la-televisio-6f20c0",
  "perquè surti el fum": "perque-surti-el-fum-d9e2a9",
  "per tenir flors": "per-tenir-flors",
  "per guardar el cotxe": "per-guardar-el-cotxe",
  "dormitori": "dormitori",
  "sala d'estar": "sala-d-estar",
  "terrassa": "terrassa",
  "prestatge": "prestatge",
  "sofà": "sofa-ee3cf2",
  "llàmpada": "llampada-fef494",
  "butaca": "butaca",
  "catifa": "catifa",
  "planta": "planta",
  "nevera": "nevera",
  "banyera": "banyera",
  "llit": "llit",
  "escombraries": "escombraries",
  "foc": "foc",
  "armari": "armari",
  "forn": "forn",
  "aixeta": "aixeta",
  "aiguera": "aiguera",
  "microones": "microones",
  "campana": "campana",
  "a la nevera": "a-la-nevera",
  "guardem el menjar.": "guardem-el-menjar",
  "a la cuina": "a-la-cuina",
  "al forn": "al-forn",
  "fem pa.": "fem-pa",
  "a les escombraries": "a-les-escombraries",
  "a l'aiguera": "a-l-aiguera",
  "hi ha els plats bruts.": "hi-ha-els-plats-bruts",
  "coixí": "coixi-98f7d9",
  "llençol": "llencol-5a3786",
  "tauleta de nit": "tauleta-de-nit",
  "despertador": "despertador",
  "manta": "manta",
  "escriptori": "escriptori",
  "prestatgeria": "prestatgeria",
  "llençols": "llencols-2e6148",
  "vàter": "vater-4407a8",
  "paper de vàter": "paper-de-vater-d57881",
  "dutxa": "dutxa",
  "tovallola": "tovallola",
  "mirall": "mirall",
  "sabó": "sabo-b6d107",
  "esponja": "esponja",
  "on és l'antena?": "on-es-l-antena-5e041c",
  "és a la teulada": "es-a-la-teulada-afd41d",
  "de fusta": "de-fusta",
  "amb sabó": "amb-sabo-16b885",
  "on plantem flors?": "on-plantem-flors",
  "al jardí": "al-jardi-398200",
  "on guardem el cotxe?": "on-guardem-el-cotxe",
  "al garatge": "al-garatge",
  "quantes finestres hi ha?": "quantes-finestres-hi-ha",
  "hi ha tres finestres": "hi-ha-tres-finestres",
  "l'habitació": "l-habitacio-c9ec0e",
  "la cuina": "la-cuina",
  "el garatge": "el-garatge",
  "la terrassa": "la-terrassa",
  "la sala d'estar": "la-sala-d-estar",
  "la nevera": "la-nevera",
  "casa gran": "casa-gran",
  "menjador gran": "menjador-gran",
  "cuina petita": "cuina-petita",
  "dormitoris petits": "dormitoris-petits",
  "garatge net": "garatge-net",
  "lavabo net": "lavabo-net",
  "cortines brutes": "cortines-brutes",
  "terrassa bruta": "terrassa-bruta",
  "escales netes": "escales-netes",
  "cui": "cui",
  "na": "na",
  "bal": "bal",
  "có": "co-01365a",
  "cor": "cor",
  "tina": "tina",
  "ne": "ne",
  "vera": "vera",
  "mi": "mi",
  "rall": "rall",
  "per": "per",
  "siana": "siana",
  "a la sala d'estar hi ha un": "a-la-sala-d-estar-hi-ha-un",
  "a la cuina hi ha una": "a-la-cuina-hi-ha-una",
  "al lavabo hi ha una": "al-lavabo-hi-ha-una",
  "al dormitori hi ha un": "al-dormitori-hi-ha-un",
  "a la sala d'estar hi ha una": "a-la-sala-d-estar-hi-ha-una",
  "on dorms.": "on-dorms",
  "on poses el teu cap.": "on-poses-el-teu-cap",
  "te la poses a sobre quan tens fred.": "te-la-poses-a-sobre-quan-ten-48c263",
  "el configures quan necessites aixecar-te aviat.": "el-configures-quan-necessite-f7419a",
  "aquí guardes la teva roba.": "aqui-guardes-la-teva-roba-4c7636",
  "vesteixes el llit amb elles.": "vesteixes-el-llit-amb-elles",
  "dormim a": "dormim-a",
  "mengem a": "mengem-a",
  "cuinem a": "cuinem-a",
  "ens rentem a": "ens-rentem-a",
  "guardem el cotxe a": "guardem-el-cotxe-a",
  "prenem el sol a": "prenem-el-sol-a",
  "mirem la televisió a": "mirem-la-televisio-a-a53ac4",
  "guardem el menjar a": "guardem-el-menjar-a",
  "llegeix i copia:": "llegeix-i-copia",
  "busca 6 paraules relacionades amb la casa. poden anar": "busca-6-paraules-relacionade-1cbb93",
  "classifica:": "classifica",
  "escriu les parts de la casa:": "escriu-les-parts-de-la-casa",
  "completa:": "completa",
  "relaciona i copia:": "relaciona-i-copia",
  "observa: sala d'estar. llegeix i copia:": "observa-sala-d-estar-llegeix-75af42",
  "observa: cuina. llegeix i copia:": "observa-cuina-llegeix-i-copi-d82f33",
  "relaciona:": "relaciona",
  "observa: dormitori. llegeix i copia:": "observa-dormitori-llegeix-i--00b074",
  "llegeix i endevina quina part del dormitori és:": "llegeix-i-endevina-quina-par-e98656",
  "observa: lavabo o bany. llegeix i copia:": "observa-lavabo-o-bany-llegei-4a6ee7",
  "relaciona la pregunta amb la resposta:": "relaciona-la-pregunta-amb-la-b1231f",
  "classifica: on trobem cada cosa?": "classifica-on-trobem-cada-co-bc76ea",
  "escriu el contrari:": "escriu-el-contrari",
  "ordena les oracions:": "ordena-les-oracions",
  "llegeix el text: «cada dia al matí obro la finestra del meu dormitori i pujo la persiana. avui la persiana s'ha trencat. el meu pare l'ha arreglat, però s'ha tornat a trencar. això no pot passar a la finestra de la cuina perquè no té persiana. la meva mare ha posat una cortina de color blanc amb flors. al menjador, també tenim una cortina blanca.» digues quantes vegades surten les paraules:": "llegeix-el-text-cada-dia-al--0844bb",
  "autoavaluació: la casa": "autoavaluacio-la-casa-4f25d3",
  "persianes": "persianes",
  "antenes": "antenes",
  "garatges": "garatges",
  "mantes": "mantes",
  "coixins": "coixins",
  "rentamans": "rentamans",
  "el jardí": "el-jardi-6dc847",
  "el dormitori": "el-dormitori",
  "l'armari": "l-armari",
  "3 persiana": "3-persiana",
  "2 finestra": "2-finestra",
  "2 cortina": "2-cortina",
  "teulada, per protegir de la pluja": "teulada-per-protegir-de-la-p-236686",
  "escala, per pujar al pis de dalt": "escala-per-pujar-al-pis-de-d-c28b68",
  "antena, per veure la televisió": "antena-per-veure-la-televisi-13b285",
  "xemeneia, perquè surti el fum": "xemeneia-perque-surti-el-fum-472da9",
  "jardí, per tenir flors": "jardi-per-tenir-flors-bc4dfd",
  "garatge, per guardar el cotxe": "garatge-per-guardar-el-cotxe",
  "a la nevera, guardem el menjar.": "a-la-nevera-guardem-el-menja-2c9eba",
  "a la cuina, cuinem tot el que mengem.": "a-la-cuina-cuinem-tot-el-que-1f5cca",
  "al forn, fem pa.": "al-forn-fem-pa",
  "a les escombraries, tirem allò que ja no serveix.": "a-les-escombraries-tirem-all-35d779",
  "a l'aiguera, hi ha els plats bruts.": "a-l-aiguera-hi-ha-els-plats--161efc",
  "on és l'antena?, és a la teulada": "on-es-l-antena-es-a-la-teula-72f01c",
  "de què està feta la taula?, de fusta": "de-que-esta-feta-la-taula-de-e5ddf0",
  "amb què ens rentem les mans?, amb sabó": "amb-que-ens-rentem-les-mans--5bd8dd",
  "on plantem flors?, al jardí": "on-plantem-flors-al-jardi-fcf815",
  "on guardem el cotxe?, al garatge": "on-guardem-el-cotxe-al-garat-53bcd7",
  "quantes finestres hi ha?, hi ha tres finestres": "quantes-finestres-hi-ha-hi-h-410e0a",
  "la xemeneia": "la-xemeneia",
  "la teulada": "la-teulada",
  "la escala": "la-escala",
  "la cortina": "la-cortina",
  "el balcó": "el-balco-8ff1fa",
  "les persianes": "les-persianes",
  "les antenes": "les-antenes",
  "els garatges": "els-garatges",
  "borja": "borja",
  "sofia": "sofia",
  "jaume": "jaume",
  "fiona": "fiona",
  "miquel": "miquel",
  "anna": "anna",
  "l'avi": "l-avi",
  "l'àvia": "l-avia-eb5d6b",
  "el pare": "el-pare",
  "la mare": "la-mare",
  "la germana": "la-germana",
  "tieta": "tieta",
  "oncle": "oncle",
  "cosina": "cosina",
  "germà": "germa-717abb",
  "tietes": "tietes",
  "àvia": "avia-2a68b7",
  "germana": "germana",
  "nét": "net-de27f0",
  "germanes": "germanes",
  "cosins": "cosins",
  "mare": "mare",
  "tia": "tia",
  "germans": "germans",
  "el bebè": "el-bebe-d7c5de",
  "gos": "gos",
  "conill": "conill",
  "hàmster": "hamster-e64a34",
  "ocell": "ocell",
  "tortuga": "tortuga",
  "peix": "peix",
  "serp": "serp",
  "cavall": "cavall",
  "fill": "fill",
  "filla": "filla",
  "avi": "avi",
  "cosí": "cosi-ef05f3",
  "marit": "marit",
  "dona": "dona",
  "ger": "ger",
  "bot": "bot",
  "à": "a-10738f",
  "via": "via",
  "on": "on",
  "cle": "cle",
  "el pare es diu": "el-pare-es-diu",
  "la mare es diu": "la-mare-es-diu",
  "el fill es diu": "el-fill-es-diu",
  "la filla es diu": "la-filla-es-diu",
  "l'avi es diu": "l-avi-es-diu",
  "l'àvia es diu": "l-avia-es-diu-33524f",
  "és l'avi o l'àvia de l'albert? és": "es-l-avi-o-l-avia-de-l-alber-25db18",
  "és l'àvia o la mare de l'albert? és": "es-l-avia-o-la-mare-de-l-alb-0b6299",
  "és l'avi o el pare de l'albert? és": "es-l-avi-o-el-pare-de-l-albe-3dc57d",
  "és la mare o la germana de l'albert? és": "es-la-mare-o-la-germana-de-l-61013d",
  "ella és la germana de la meva mare. és la meva": "ella-es-la-germana-de-la-mev-d0f9fb",
  "ell és el marit de la meva tieta. és el meu": "ell-es-el-marit-de-la-meva-t-edcc9b",
  "ella és la filla del meu oncle i de la meva tieta. és la meva": "ella-es-la-filla-del-meu-onc-16e16e",
  "la mare té els cabells curts.": "la-mare-te-els-cabells-curts-6ba8ef",
  "el pare és més alt que la mare.": "el-pare-es-mes-alt-que-la-ma-08d9d6",
  "el pare té els cabells curts.": "el-pare-te-els-cabells-curts-40a6e3",
  "la mare té els cabells llargs.": "la-mare-te-els-cabells-llarg-3f1ea8",
  "el fill té la samarreta vermella.": "el-fill-te-la-samarreta-verm-50fadf",
  "el pare té la samarreta lila.": "el-pare-te-la-samarreta-lila-8d342b",
  "el fill té els cabells del mateix color que el pare.": "el-fill-te-els-cabells-del-m-43bd8a",
  "el pare de la mare és": "el-pare-de-la-mare-es-182dd8",
  "la mare del pare és": "la-mare-del-pare-es-f84cac",
  "la filla de l'avi i l'àvia és": "la-filla-de-l-avi-i-l-avia-e-ecd23d",
  "el fill de l'avi i l'àvia és": "el-fill-de-l-avi-i-l-avia-es-114c74",
  "la filla és la del fill.": "la-filla-es-la-del-fill-e23e5f",
  "en cesc té un ocell?": "en-cesc-te-un-ocell-b3ddc8",
  "la carlota té un gos?": "la-carlota-te-un-gos-6e21ac",
  "en cesc té un gat?": "en-cesc-te-un-gat-e45ba7",
  "la carlota té un hàmster?": "la-carlota-te-un-hamster-19031d",
  "observa i completa els noms de la família:": "observa-i-completa-els-noms--e60945",
  "observa l'arbre genealògic i completa:": "observa-l-arbre-genealogic-i-5ce09d",
  "observa i completa:": "observa-i-completa",
  "observa i respon. jo soc l'albert.": "observa-i-respon-jo-soc-l-al-de2edc",
  "completa amb la, el, les o els:": "completa-amb-la-el-les-o-els",
  "separa les paraules i copia:": "separa-les-paraules-i-copia",
  "observa i marca les oracions correctes:": "observa-i-marca-les-oracions-1fff4c",
  "relaciona cada membre de la família amb la seva paraula.": "relaciona-cada-membre-de-la--761b5d",
  "cerca i copia 6 animals. poden anar": "cerca-i-copia-6-animals-pode-056924",
  "llegeix el que han contestat la carlota i en cesc a la pregunta: quines mascotes tens?": "llegeix-el-que-han-contestat-e8ee94",
  "autoavaluació: la família": "autoavaluacio-la-familia-0d6771",
  "• el pare es diu borja.": "el-pare-es-diu-borja",
  "• la mare es diu sofia.": "la-mare-es-diu-sofia",
  "• el fill es diu jaume.": "el-fill-es-diu-jaume",
  "• la filla es diu fiona.": "la-filla-es-diu-fiona",
  "• l'avi es diu miquel.": "l-avi-es-diu-miquel",
  "• l'àvia es diu anna.": "l-avia-es-diu-anna-9f7481",
  "jo soc l'albert.": "jo-soc-l-albert",
  "nebot": "nebot",
  "neboda": "neboda",
  "meva": "meva",
  "es": "es",
  "diu": "diu",
  "anna.": "anna",
  "meu": "meu",
  "sergi.": "sergi",
  "ona.": "ona",
  "joan.": "joan",
  "l'oncle": "l-oncle",
  "la tieta": "la-tieta",
  "la filla": "la-filla",
  "el fill": "el-fill",
  "hamster": "hamster",
  "el germà": "el-germa-1ef96d",
  "les tietes": "les-tietes",
  "la àvia": "la-avia-f649b6",
  "el nét": "el-net-01d45a",
  "les germanes": "les-germanes",
  "els cosins": "els-cosins",
  "el oncle": "el-oncle",
  "la tia": "la-tia",
  "els germans": "els-germans",
  "el cosí": "el-cosi-4dfc4d",
  "el marit": "el-marit",
  "el avi": "el-avi",
  "el nebot": "el-nebot",
  "la cosina": "la-cosina",
  "la dona": "la-dona",
  "la neboda": "la-neboda",
  "fruiteria": "fruiteria",
  "verduleria": "verduleria",
  "peixeteria": "peixeteria",
  "carnisseria": "carnisseria",
  "fleca": "fleca",
  "farmàcia": "farmacia-d058c2",
  "supermercat": "supermercat",
  "botiga d'esports": "botiga-d-esports",
  "poma": "poma",
  "pera": "pera",
  "plàtan": "platan-721817",
  "maduixa": "maduixa",
  "cirera": "cirera",
  "préssec": "pressec-4592f8",
  "meló": "melo-7266ba",
  "síndria": "sindria-ad32ee",
  "ceba": "ceba",
  "enciam": "enciam",
  "pastanaga": "pastanaga",
  "patata": "patata",
  "pebrot": "pebrot",
  "tomàquet": "tomaquet-c224a7",
  "mongetes": "mongetes",
  "sardina": "sardina",
  "tonyina": "tonyina",
  "salmó": "salmo-12bc4e",
  "calamar": "calamar",
  "gamba": "gamba",
  "musclo": "musclo",
  "sardines": "sardines",
  "tonyines": "tonyines",
  "salmons": "salmons",
  "calamars": "calamars",
  "gambes": "gambes",
  "musclos": "musclos",
  "pollastre": "pollastre",
  "salsitxa": "salsitxa",
  "mandonguilla": "mandonguilla",
  "hamburguesa": "hamburguesa",
  "bistec": "bistec",
  "cansalada": "cansalada",
  "barra de pa": "barra-de-pa",
  "pa rodó": "pa-rodo-ac3fb5",
  "pa de motlle": "pa-de-motlle",
  "pastís": "pastis-41d98a",
  "croissant": "croissant",
  "galeta": "galeta",
  "vaig": "vaig",
  "aniré": "anire-cc45c7",
  "tirita": "tirita",
  "pastilla": "pastilla",
  "xeringa": "xeringa",
  "termòmetre": "termometre-3fab65",
  "cotó": "coto-f619af",
  "venda": "venda",
  "fle": "fle",
  "frui": "frui",
  "teria": "teria",
  "car": "car",
  "nisseria": "nisseria",
  "far": "far",
  "màcia": "macia-420dc8",
  "pei": "pei",
  "xeteria": "xeteria",
  "verdu": "verdu",
  "leria": "leria",
  "compro peix a la": "compro-peix-a-la",
  "compro pa a la": "compro-pa-a-la",
  "compro fruita a la": "compro-fruita-a-la",
  "compro medicaments a la": "compro-medicaments-a-la",
  "compro carn a la": "compro-carn-a-la",
  "pinta la ceba de color groc": "pinta-la-ceba-de-color-groc",
  "pinta l'enciam de color verd": "pinta-l-enciam-de-color-verd",
  "pinta la pastanaga de color taronja": "pinta-la-pastanaga-de-color--d11252",
  "pinta la patata de color marró": "pinta-la-patata-de-color-mar-3be49b",
  "pinta el pebrot de color vermell": "pinta-el-pebrot-de-color-ver-fe4221",
  "pinta el tomàquet de color vermell": "pinta-el-tomaquet-de-color-v-3fcd28",
  "pinta les mongetes de color verd": "pinta-les-mongetes-de-color--767a9c",
  "la és de color taronja.": "la-es-de-color-taronja-88663e",
  "el és de color vermell.": "el-es-de-color-vermell-3d205b",
  "l' és verd i el mengem a l'amanida.": "l-es-verd-i-el-mengem-a-l-am-83cf3e",
  "la fa plorar quan la tallem.": "la-fa-plorar-quan-la-tallem",
  "ahir anar a la fruiteria.": "ahir-anar-a-la-fruiteria",
  "avui a la fleca.": "avui-a-la-fleca",
  "demà a la peixeteria.": "dema-a-la-peixeteria-9fbb2d",
  "ahir comprar sardines.": "ahir-comprar-sardines",
  "llegeix i copia les botigues:": "llegeix-i-copia-les-botigues",
  "completa la frase:": "completa-la-frase",
  "separa i copia les oracions:": "separa-i-copia-les-oracions",
  "llegeix i copia les fruites:": "llegeix-i-copia-les-fruites",
  "completa les lletres que falten:": "completa-les-lletres-que-fal-bcc23c",
  "llegeix i copia les verdures:": "llegeix-i-copia-les-verdures",
  "pinta les verdures del color correcte:": "pinta-les-verdures-del-color-77e4c0",
  "completa amb el nom de la verdura:": "completa-amb-el-nom-de-la-ve-08f61c",
  "llegeix i copia el peix:": "llegeix-i-copia-el-peix",
  "llegeix i copia la carn:": "llegeix-i-copia-la-carn",
  "classifica: el o la?": "classifica-el-o-la",
  "llegeix i copia els productes de la fleca:": "llegeix-i-copia-els-producte-eeef2e",
  "classifica els productes a la seva botiga:": "classifica-els-productes-a-l-988609",
  "completa amb el verb correcte:": "completa-amb-el-verb-correct-c5ebb5",
  "llegeix i copia els productes de la farmàcia:": "llegeix-i-copia-els-producte-b033dc",
  "classifica: a quina botiga ho compres?": "classifica-a-quina-botiga-ho-2ac03e",
  "ven": "ven",
  "peix.": "peix",
  "compro": "compro",
  "fleca.": "fleca",
  "medicaments.": "medicaments",
  "carn.": "carn",
  "botiga": "botiga",
  "d'esports": "d-esports",
  "venen": "venen",
  "bambes.": "bambes",
  "vaig anar": "vaig-anar",
  "anava": "anava",
  "compraré": "comprare-0a332a",
  "infermera": "infermera",
  "posa": "posa",
  "una": "una",
  "tirita.": "tirita",
  "prenc": "prenc",
  "culleres": "culleres",
  "xarop.": "xarop",
  "protegeix": "protegeix",
  "ferida.": "ferida",
  "sardina, sardines": "sardina-sardines",
  "tonyina, tonyines": "tonyina-tonyines",
  "salmó, salmons": "salmo-salmons-4de005",
  "calamar, calamars": "calamar-calamars",
  "gamba, gambes": "gamba-gambes",
  "musclo, musclos": "musclo-musclos",
  "el pollastre": "el-pollastre",
  "el bistec": "el-bistec",
  "la salsitxa": "la-salsitxa",
  "la mandonguilla": "la-mandonguilla",
  "la hamburguesa": "la-hamburguesa",
  "la cansalada": "la-cansalada",
  "tassa": "tassa",
  "ampolla": "ampolla",
  "got": "got",
  "copa": "copa",
  "ganivet": "ganivet",
  "cullera": "cullera",
  "forquilla": "forquilla",
  "plat": "plat",
  "tovalló": "tovallo-552cad",
  "tasses": "tasses",
  "ampolles": "ampolles",
  "gots": "gots",
  "copes": "copes",
  "ganivets": "ganivets",
  "forquilles": "forquilles",
  "plats": "plats",
  "tovallons": "tovallons",
  "suc": "suc",
  "cafè": "cafe-f3b4b4",
  "pa de pessic": "pa-de-pessic",
  "te": "te",
  "cereals": "cereals",
  "llet": "llet",
  "galetes": "galetes",
  "entrepà": "entrepa-98606f",
  "fruita": "fruita",
  "arròs": "arros-51014b",
  "sandvitx": "sandvitx",
  "sopa": "sopa",
  "verdures": "verdures",
  "macarrons": "macarrons",
  "amanida": "amanida",
  "patates fregides": "patates-fregides",
  "aigua": "aigua",
  "refresc": "refresc",
  "iogurt": "iogurt",
  "truita de patates": "truita-de-patates",
  "pizza": "pizza",
  "formatge": "formatge",
  "pernil": "pernil",
  "bec el cafè amb...": "bec-el-cafe-amb-1ef93c",
  "menjo l'amanida amb...": "menjo-l-amanida-amb",
  "tallo la carn amb...": "tallo-la-carn-amb",
  "menjo la sopa amb...": "menjo-la-sopa-amb",
  "poso el menjar al...": "poso-el-menjar-al",
  "bec aigua amb...": "bec-aigua-amb",
  "gelat": "gelat",
  "estovalles": "estovalles",
  "fred": "fred",
  "calenta": "calenta",
  "calent": "calent",
  "freda": "freda",
  "dinaràs": "dinaras-8f2e4b",
  "berenaràs": "berenaras-b067ae",
  "esmorzaràs": "esmorzaras-be7249",
  "cu": "cu",
  "llera": "llera",
  "ga": "ga",
  "nivet": "nivet",
  "for": "for",
  "quilla": "quilla",
  "am": "am",
  "polla": "polla",
  "tas": "tas",
  "sa": "sa",
  "matge": "matge",
  "per esmorzar menjo amb llet.": "per-esmorzar-menjo-amb-llet",
  "per dinar menjo amb verdures.": "per-dinar-menjo-amb-verdures",
  "per berenar menjo un": "per-berenar-menjo-un",
  "per sopar menjo": "per-sopar-menjo",
  "què mengem per esmorzar normalment?": "que-mengem-per-esmorzar-norm-4b597a",
  "amb què tallem el menjar?": "amb-que-tallem-el-menjar-e41e1c",
  "on posem la sopa?": "on-posem-la-sopa",
  "quin àpat fem al migdia?": "quin-apat-fem-al-migdia-1045c4",
  "pinta el gelat de color blau (fred)": "pinta-el-gelat-de-color-blau-253633",
  "pinta la sopa de color vermell (calent)": "pinta-la-sopa-de-color-verme-f75889",
  "pinta el cafè de color vermell (calent)": "pinta-el-cafe-de-color-verme-aefd3a",
  "pinta el suc de color blau (fred)": "pinta-el-suc-de-color-blau-f-79866f",
  "pinta la pizza de color vermell (calent)": "pinta-la-pizza-de-color-verm-972ead",
  "pinta l'iogurt de color blau (fred)": "pinta-l-iogurt-de-color-blau-4a18cf",
  "pinta el te de color vermell (calent)": "pinta-el-te-de-color-vermell-d18c0d",
  "pinta el refresc de color blau (fred)": "pinta-el-refresc-de-color-bl-26e1a1",
  "a la hi ha suc fresc.": "a-la-hi-ha-suc-fresc",
  "quan em taco, em netejo amb el": "quan-em-taco-em-netejo-amb-e-968a96",
  "m'encanta vestir la taula del menjador amb unes boniques": "m-encanta-vestir-la-taula-de-9552ea",
  "el gelat és": "el-gelat-es-833a5d",
  "la pizza és": "la-pizza-es-4d7568",
  "el cafè és": "el-cafe-es-9b8e09",
  "la fruita és": "la-fruita-es-261921",
  "quin primer plat pots triar al restaurant?": "quin-primer-plat-pots-triar--a8d7e3",
  "quin segon plat hi ha amb patates?": "quin-segon-plat-hi-ha-amb-pa-479527",
  "què pots prendre de postres?": "que-pots-prendre-de-postres-c9494b",
  "quina beguda ofereix el menú?": "quina-beguda-ofereix-el-menu-31625f",
  "què? — per dinar tinc macarrons amb tomàquet.": "que-per-dinar-tinc-macarrons-462d5f",
  "què? — per berenar menjo pa amb xocolata.": "que-per-berenar-menjo-pa-amb-07205e",
  "què? — per esmorzar menjo galetes amb llet.": "que-per-esmorzar-menjo-galet-b5e8df",
  "llegeix i copia els estris de cuina:": "llegeix-i-copia-els-estris-d-c81df9",
  "llegeix i copia els aliments de l'esmorzar:": "llegeix-i-copia-els-aliments-f5178d",
  "completa les frases sobre els àpats:": "completa-les-frases-sobre-el-1ac35d",
  "llegeix i copia els aliments del dinar:": "llegeix-i-copia-els-aliments-255976",
  "tria la resposta correcta:": "tria-la-resposta-correcta",
  "llegeix i copia els aliments del berenar i el sopar:": "llegeix-i-copia-els-aliments-3fcdbb",
  "classifica: per menjar o per beure?": "classifica-per-menjar-o-per--7c19e4",
  "relaciona cada frase amb l'estri correcte:": "relaciona-cada-frase-amb-l-e-dabfd5",
  "classifica: fred o calent?": "classifica-fred-o-calent",
  "pinta de blau el menjar fred i de vermell el calent:": "pinta-de-blau-el-menjar-fred-1561a1",
  "observa i copia:": "observa-i-copia",
  "completa les frases:": "completa-les-frases",
  "classifica: dolç o salat?": "classifica-dolc-o-salat-f21177",
  "completa amb fred, freda, calent o calenta:": "completa-amb-fred-freda-cale-6eba7d",
  "llegeix el menú del restaurant tot bo i contesta:": "llegeix-el-menu-del-restaura-6dab6c",
  "completa la pregunta per cada resposta:": "completa-la-pregunta-per-cad-79f4af",
  "classifica: fruita o verdura?": "classifica-fruita-o-verdura",
  "cereals amb llet": "cereals-amb-llet",
  "sopa de peix": "sopa-de-peix",
  "al got": "al-got",
  "al plat": "al-plat",
  "a la copa": "a-la-copa",
  "a la forquilla": "a-la-forquilla",
  "esmorzar": "esmorzar",
  "berenar": "berenar",
  "sopar": "sopar",
  "dinar": "dinar",
  "menjo": "menjo",
  "amb": "amb",
  "tomàquet.": "tomaquet-2a8863",
  "beure": "beure",
  "cafè.": "cafe-f83e9d",
  "poso": "poso",
  "menjar": "menjar",
  "al": "al",
  "damunt": "damunt",
  "del": "del",
  "plat.": "plat",
  "llet.": "llet",
  "pastís de xocolata": "pastis-de-xocolata-8e770d",
  "xocolata": "xocolata",
  "caramels": "caramels",
  "sucre": "sucre",
  "sal": "sal",
  "hamburguesa amb patates": "hamburguesa-amb-patates",
  "fruita amb gelat": "fruita-amb-gelat",
  "cafè amb llet": "cafe-amb-llet-2d740c",
  "soparàs": "soparas-7a5dc2",
  "tassa, tasses": "tassa-tasses",
  "ampolla, ampolles": "ampolla-ampolles",
  "got, gots": "got-gots",
  "copa, copes": "copa-copes",
  "ganivet, ganivets": "ganivet-ganivets",
  "cullera, culleres": "cullera-culleres",
  "forquilla, forquilles": "forquilla-forquilles",
  "plat, plats": "plat-plats",
  "tovalló, tovallons": "tovallo-tovallons-ce6959",
  "bec el cafè amb..., tassa": "bec-el-cafe-amb-tassa-b30807",
  "menjo l'amanida amb..., forquilla": "menjo-l-amanida-amb-forquill-1d9853",
  "tallo la carn amb..., ganivet": "tallo-la-carn-amb-ganivet",
  "menjo la sopa amb..., cullera": "menjo-la-sopa-amb-cullera",
  "poso el menjar al..., plat": "poso-el-menjar-al-plat",
  "bec aigua amb..., got": "bec-aigua-amb-got",
  "gallina": "gallina",
  "gall": "gall",
  "pollet": "pollet",
  "flamenc": "flamenc",
  "cigonya": "cigonya",
  "gavina": "gavina",
  "pingüí": "pingui-2ef6ab",
  "estruç": "estruc-b8c8d2",
  "mussol": "mussol",
  "oreneta": "oreneta",
  "plomes": "plomes",
  "ous": "ous",
  "ales": "ales",
  "dues": "dues",
  "bec": "bec",
  "mosca": "mosca",
  "formiga": "formiga",
  "abella": "abella",
  "escarabat": "escarabat",
  "papallona": "papallona",
  "mosquit": "mosquit",
  "tauró": "tauro-c0ea0b",
  "ànec": "anec-d42847",
  "oca": "oca",
  "granota": "granota",
  "unicorn": "unicorn",
  "mamífer": "mamifer-edf344",
  "au": "au",
  "rèptil": "reptil-df24f5",
  "insecte": "insecte",
  "cocodril": "cocodril",
  "porc": "porc",
  "vaca": "vaca",
  "ratolí": "ratoli-df4af4",
  "ovella": "ovella",
  "hipopòtam": "hipopotam-39e29c",
  "goril·la": "goril-la",
  "zebra": "zebra",
  "ós": "os-16a563",
  "lleó": "lleo-31045b",
  "camell": "camell",
  "elefant": "elefant",
  "tigre": "tigre",
  "llop": "llop",
  "guineu": "guineu",
  "gossa": "gossa",
  "lleona": "lleona",
  "gata": "gata",
  "óssa": "ossa-022f3b",
  "conilla": "conilla",
  "tigressa": "tigressa",
  "elefanta": "elefanta",
  "neda": "neda",
  "vola": "vola",
  "camina": "camina",
  "s'arrossega": "s-arrossega",
  "conills": "conills",
  "gran": "gran",
  "llina": "llina",
  "nill": "nill",
  "tor": "tor",
  "tuga": "tuga",
  "gi": "gi",
  "rafa": "rafa",
  "mus": "mus",
  "sol": "sol",
  "papa": "papa",
  "llona": "llona",
  "les aus tenen el cos cobert de": "les-aus-tenen-el-cos-cobert--080f1b",
  "neixen dels": "neixen-dels",
  "tenen per poder volar.": "tenen-per-poder-volar",
  "tenen potes.": "tenen-potes",
  "nosaltres tenim boca i les aus tenen": "nosaltres-tenim-boca-i-les-a-18cf21",
  "pinta el lleó de color groc": "pinta-el-lleo-de-color-groc-31e5c2",
  "pinta la gavina de color blau": "pinta-la-gavina-de-color-bla-8d2e7e",
  "pinta el cocodril de color verd": "pinta-el-cocodril-de-color-v-2b895d",
  "pinta el ratolí de color marró": "pinta-el-ratoli-de-color-mar-132fcc",
  "pinta el tauró de color negre": "pinta-el-tauro-de-color-negr-6c75b1",
  "pinta la serp de color taronja": "pinta-la-serp-de-color-taron-c8f521",
  "pinta el conill de color rosa": "pinta-el-conill-de-color-ros-909995",
  "pinta la vaca de color vermell": "pinta-la-vaca-de-color-verme-034356",
  "pinta la tortuga de color lila": "pinta-la-tortuga-de-color-li-59112b",
  "amb què vola l'au?": "amb-que-vola-l-au-42b11a",
  "amb què menja l'au?": "amb-que-menja-l-au-887f3a",
  "de què està cobert el cos de l'au?": "de-que-esta-cobert-el-cos-de-d44da9",
  "amb què camina l'au per terra?": "amb-que-camina-l-au-per-terr-64b94f",
  "què té l'au al darrere per dirigir el vol?": "que-te-l-au-al-darrere-per-d-ae6fd5",
  "el tauró": "el-tauro-93672f",
  "el mussol": "el-mussol",
  "el gos": "el-gos",
  "la serp": "la-serp",
  "l'elefant": "l-elefant",
  "la sardina": "la-sardina",
  "com és l'ós?": "com-es-l-os-281a04",
  "com és el cavall?": "com-es-el-cavall-de2077",
  "com és la papallona?": "com-es-la-papallona-5ba566",
  "com és el tauró?": "com-es-el-tauro-881f45",
  "la serp menja rates i": "la-serp-menja-rates-i",
  "la granota és de color": "la-granota-es-de-color-011a61",
  "l'elefant és un animal molt": "l-elefant-es-un-animal-molt-aab8ac",
  "la serp té potes?": "la-serp-te-potes-1a7325",
  "com es mou la serp?": "com-es-mou-la-serp",
  "la serp és un...": "la-serp-es-un-fa0a2e",
  "mamífer amb orelles grans i una gran trompa:": "mamifer-amb-orelles-grans-i--585ef0",
  "rèptil perillos, amb moltes dents, de color verd:": "reptil-perillos-amb-moltes-d-229ef6",
  "rèptil verinós, llarg, que s'arrossega:": "reptil-verinos-llarg-que-s-a-49decc",
  "viu a la selva, taronja i negre, sembla un gat gran:": "viu-a-la-selva-taronja-i-neg-220bd5",
  "llegeix i copia les aus:": "llegeix-i-copia-les-aus",
  "completa les frases sobre les aus:": "completa-les-frases-sobre-le-517145",
  "llegeix i copia els insectes:": "llegeix-i-copia-els-insectes",
  "classifica cada animal a la seva categoria:": "classifica-cada-animal-a-la--512324",
  "llegeix i copia els peixos:": "llegeix-i-copia-els-peixos",
  "classifica: animal domèstic o salvatge?": "classifica-animal-domestic-o-172ff3",
  "llegeix i copia aquests animals:": "llegeix-i-copia-aquests-anim-000288",
  "relaciona cada animal amb la seva categoria:": "relaciona-cada-animal-amb-la-44e39e",
  "llegeix i copia els rèptils:": "llegeix-i-copia-els-reptils-2d3a8b",
  "classifica: un o una?": "classifica-un-o-una",
  "llegeix i copia els mamífers: (1 de 3).": "llegeix-i-copia-els-mamifers-460746",
  "busca 8 mamífers a la sopa de lletres. poden anar": "busca-8-mamifers-a-la-sopa-d-719929",
  "llegeix i copia els mamífers: (2 de 3).": "llegeix-i-copia-els-mamifers-28ba9c",
  "pinta cada animal del color que et diu:": "pinta-cada-animal-del-color--fe3679",
  "llegeix i copia els mamífers: (3 de 3).": "llegeix-i-copia-els-mamifers-08f44f",
  "les parts de l'au. tria la resposta correcta:": "les-parts-de-l-au-tria-la-re-fe184c",
  "relaciona el masculí amb el femení:": "relaciona-el-masculi-amb-el--d2ab5c",
  "què fan els animals? completa:": "que-fan-els-animals-completa-00d70c",
  "tria la descripció correcta:": "tria-la-descripcio-correcta-958e7d",
  "completa les oracions sobre els animals:": "completa-les-oracions-sobre--8326e9",
  "mira la serp i respon:": "mira-la-serp-i-respon",
  "endevina quin animal és:": "endevina-quin-animal-es-f9d7ec",
  "escates": "escates",
  "pel": "pel",
  "arbres": "arbres",
  "rius": "rius",
  "potes": "potes",
  "cua": "cua",
  "quatre": "quatre",
  "sis": "sis",
  "girafa": "girafa",
  "mico": "mico",
  "dofí": "dofi-79cdf4",
  "lleo": "lleo",
  "os": "os",
  "pèl": "pel-b89d03",
  "gran, mamífer, cobert de pel, viu al bosc": "gran-mamifer-cobert-de-pel-v-6c513c",
  "petit, insecte, té ales, viu a les flors": "petit-insecte-te-ales-viu-a--90614e",
  "llarg, rèptil, s'arrossega, viu al riu": "llarg-reptil-s-arrossega-viu-50e904",
  "petit, peix, neda, viu al mar": "petit-peix-neda-viu-al-mar",
  "petit, té escates, neda al mar": "petit-te-escates-neda-al-mar-e9d013",
  "gran, mamífer, cobert de pel, camina": "gran-mamifer-cobert-de-pel-c-0a24d1",
  "petit, insecte, vola, té 6 potes": "petit-insecte-vola-te-6-pote-a9dc8f",
  "gran, rèptil, s'arrossega": "gran-reptil-s-arrossega-741a47",
  "gran, mamífer, camina": "gran-mamifer-camina-80f736",
  "petit, rèptil, s'arrossega": "petit-reptil-s-arrossega-0a0a70",
  "petit, insecte, vola, té ales de colors": "petit-insecte-vola-te-ales-d-ef3e9e",
  "gran, au, neda": "gran-au-neda",
  "petit, insecte, vola": "petit-insecte-vola",
  "gran, au, camina": "gran-au-camina",
  "gran, peix, neda, perillos, viu al mar": "gran-peix-neda-perillos-viu--d25490",
  "flors": "flors",
  "petit": "petit",
  "gat, mamífer": "gat-mamifer-dd4f98",
  "sardina, peix": "sardina-peix",
  "flamenc, au": "flamenc-au",
  "serp, rèptil": "serp-reptil-c93208",
  "papallona, insecte": "papallona-insecte",
  "gos, gossa": "gos-gossa",
  "lleó, lleona": "lleo-lleona-3a9819",
  "gat, gata": "gat-gata",
  "ós, óssa": "os-ossa-27cc5d",
  "conill, conilla": "conill-conilla",
  "gall, gallina": "gall-gallina",
  "tigre, tigressa": "tigre-tigressa",
  "elefant, elefanta": "elefant-elefanta",
  "un gos": "un-gos",
  "un gat": "un-gat",
  "un lleó": "un-lleo-097aea",
  "un dofí": "un-dofi-6bec26",
  "un cavall": "un-cavall",
  "un elefant": "un-elefant",
  "una vaca": "una-vaca",
  "una zebra": "una-zebra",
  "una ovella": "una-ovella",
  "una guineu": "una-guineu",
  "una serp": "una-serp",
  "una tortuga": "una-tortuga",
  "carrer": "carrer",
  "plaça": "placa-eb562e",
  "hospital": "hospital",
  "escola": "escola",
  "estació": "estacio-a2679f",
  "museu": "museu",
  "restaurant": "restaurant",
  "semàfor": "semafor-325627",
  "curar-se": "curar-se",
  "estudiar": "estudiar",
  "veure pel·lícules": "veure-pel-licules-0386f9",
  "jugar": "jugar",
  "passejar": "passejar",
  "comprar": "comprar",
  "viatjar": "viatjar",
  "pas de vianants": "pas-de-vianants",
  "parada d'autobús": "parada-d-autobus-f02e1a",
  "fanal": "fanal",
  "rer": "rer",
  "pla": "pla",
  "ça": "ca-01819e",
  "hos": "hos",
  "pital": "pital",
  "mu": "mu",
  "seu": "seu",
  "ci": "ci",
  "nema": "nema",
  "tea": "tea",
  "tre": "tre",
  "anem al per veure una pel·lícula.": "anem-al-per-veure-una-pel-li-8f3aaa",
  "comprem al": "comprem-al",
  "juguem al": "juguem-al",
  "estudiem a l'": "estudiem-a-l",
  "on anem quan estem malalts?": "on-anem-quan-estem-malalts",
  "on podem veure quadres i escultures?": "on-podem-veure-quadres-i-esc-d421df",
  "on creuem el carrer amb seguretat?": "on-creuem-el-carrer-amb-segu-42787e",
  "on agafem el tren?": "on-agafem-el-tren",
  "per comprar fruita vaig al": "per-comprar-fruita-vaig-al",
  "per llegir llibres vaig a la": "per-llegir-llibres-vaig-a-la",
  "per viatjar en tren vaig a l'": "per-viatjar-en-tren-vaig-a-l",
  "per passejar vaig al": "per-passejar-vaig-al",
  "a la meva ciutat hi ha un molt gran.": "a-la-meva-ciutat-hi-ha-un-mo-f5e1aa",
  "el és al centre de la ciutat.": "el-es-al-centre-de-la-ciutat-637c4a",
  "l' és molt moderna.": "l-es-molt-moderna-5f4018",
  "la té molts arbres.": "la-te-molts-arbres-895d34",
  "el ens indica quan podem creuar.": "el-ens-indica-quan-podem-cre-247457",
  "creuem pel quan el semàfor és verd.": "creuem-pel-quan-el-semafor-e-9aa4d9",
  "esperem l'autobús a la": "esperem-l-autobus-a-la-728862",
  "el il·lumina el carrer a la nit.": "el-il-lumina-el-carrer-a-la--dd590d",
  "llegeix i copia els llocs de la ciutat:": "llegeix-i-copia-els-llocs-de-648278",
  "ordena les lletres per formar la paraula:": "ordena-les-lletres-per-forma-acf7e7",
  "relaciona cada lloc amb el que hi fas:": "relaciona-cada-lloc-amb-el-q-dac23a",
  "troba les paraules a la sopa de lletres. poden anar": "troba-les-paraules-a-la-sopa-b7d9b1",
  "classifica: diversió o serveis?": "classifica-diversio-o-servei-bce4b5",
  "relaciona cada lloc amb què hi fas:": "relaciona-cada-lloc-amb-que--019ac5",
  "on vas? completa:": "on-vas-completa",
  "classifica: edificis vs espais oberts": "classifica-edificis-vs-espai-7d467a",
  "descriu la teva ciutat:": "descriu-la-teva-ciutat",
  "completa les frases sobre la ciutat:": "completa-les-frases-sobre-la-493096",
  "teatre": "teatre",
  "estacio": "estacio",
  "ajuntament": "ajuntament",
  "al cinema": "al-cinema",
  "a l'hospital": "a-l-hospital",
  "al parc": "al-parc",
  "al mercat": "al-mercat",
  "al restaurant": "al-restaurant",
  "a l'escola": "a-l-escola",
  "al museu": "al-museu",
  "a l'estació": "a-l-estacio-b14b88",
  "al semàfor": "al-semafor-2b85c2",
  "a la biblioteca": "a-la-biblioteca",
  "al teatre": "al-teatre",
  "a l'ajuntament": "a-l-ajuntament",
  "riu": "riu",
  "cova": "cova",
  "illa": "illa",
  "hospital, curar-se": "hospital-curar-se",
  "escola, estudiar": "escola-estudiar",
  "cinema, veure pel·lícules": "cinema-veure-pel-licules-ad9c67",
  "parc, jugar": "parc-jugar",
  "restaurant, menjar": "restaurant-menjar",
  "parc, passejar": "parc-passejar",
  "mercat, comprar": "mercat-comprar",
  "estació, viatjar": "estacio-viatjar-18084a",
  "cotxe": "cotxe",
  "autobús": "autobus-75b263",
  "tren": "tren",
  "avió": "avio-badf7a",
  "moto": "moto",
  "vaixell": "vaixell",
  "helicòpter": "helicopter-353639",
  "camió": "camio-68c6a2",
  "taxi": "taxi",
  "ambulància": "ambulancia-575e1d",
  "barca": "barca",
  "carretera": "carretera",
  "mar": "mar",
  "cel": "cel",
  "vies": "vies",
  "metro": "metro",
  "sota terra": "sota-terra",
  "txe": "txe",
  "auto": "auto",
  "bús": "bus-223fae",
  "bici": "bici",
  "cleta": "cleta",
  "mió": "mio-f9bd2d",
  "vió": "vio-3206be",
  "vai": "vai",
  "xell": "xell",
  "anem a l'escola en": "anem-a-l-escola-en",
  "viatgem per l'aire en": "viatgem-per-l-aire-en",
  "naveguem pel mar en": "naveguem-pel-mar-en",
  "anem ràpid en": "anem-rapid-en-96e5e2",
  "quin vehicle va pel cel?": "quin-vehicle-va-pel-cel",
  "quin vehicle va per les vies?": "quin-vehicle-va-per-les-vies",
  "quin vehicle té dues rodes i pedals?": "quin-vehicle-te-dues-rodes-i-fb063b",
  "quin vehicle ens porta a l'hospital?": "quin-vehicle-ens-porta-a-l-h-5f1e42",
  "el va per les vies.": "el-va-per-les-vies",
  "l' vola pel cel.": "l-vola-pel-cel",
  "l' té moltes rodes i porta molta gent.": "l-te-moltes-rodes-i-porta-mo-fbb093",
  "la té dues rodes i pedals.": "la-te-dues-rodes-i-pedals-4c755b",
  "llegeix i copia els vehicles:": "llegeix-i-copia-els-vehicles",
  "relaciona cada vehicle amb on va:": "relaciona-cada-vehicle-amb-o-2875a5",
  "classifica: terra, mar o aire?": "classifica-terra-mar-o-aire",
  "completa les frases sobre els vehicles:": "completa-les-frases-sobre-el-aa88f3",
  "classifica: terra vs mar vs aire": "classifica-terra-vs-mar-vs-a-d82f9a",
  "mira la imatge i ordena les síl·labes:": "mira-la-imatge-i-ordena-les--5190d7",
  "patinet": "patinet",
  "helicopter": "helicopter",
  "tramvia": "tramvia",
  "canoa": "canoa",
  "globus": "globus",
  "cotxe, carretera": "cotxe-carretera",
  "vaixell, mar": "vaixell-mar",
  "avió, cel": "avio-cel-c34aca",
  "tren, vies": "tren-vies",
  "metro, sota terra": "metro-sota-terra",
  "mestre": "mestre",
  "metge": "metge",
  "bomber": "bomber",
  "policia": "policia",
  "cuiner": "cuiner",
  "infermer": "infermer",
  "pilot": "pilot",
  "cambrer": "cambrer",
  "dentista": "dentista",
  "veterinari": "veterinari",
  "jardiner": "jardiner",
  "pagès": "pages-2d0d9a",
  "parc de bombers": "parc-de-bombers",
  "carter": "carter",
  "estetoscopi": "estetoscopi",
  "extintor": "extintor",
  "paella": "paella",
  "mes": "mes",
  "met": "met",
  "bom": "bom",
  "ber": "ber",
  "po": "po",
  "licia": "licia",
  "ner": "ner",
  "den": "den",
  "tista": "tista",
  "el apaga el foc.": "el-apaga-el-foc",
  "el ensenya a l'escola.": "el-ensenya-a-l-escola",
  "el cura els malalts.": "el-cura-els-malalts",
  "el porta les cartes.": "el-porta-les-cartes",
  "qui treballa a l'hospital?": "qui-treballa-a-l-hospital",
  "qui apaga els incendis?": "qui-apaga-els-incendis",
  "qui prepara el menjar al restaurant?": "qui-prepara-el-menjar-al-res-0d2174",
  "qui condueix un avió?": "qui-condueix-un-avio-f35dd5",
  "qui apaga focs?": "qui-apaga-focs",
  "qui cuida la seguretat?": "qui-cuida-la-seguretat",
  "qui cura els malalts?": "qui-cura-els-malalts",
  "qui ensenya als nens?": "qui-ensenya-als-nens",
  "el cuida els animals.": "el-cuida-els-animals",
  "l' ajuda el metge a l'hospital.": "l-ajuda-el-metge-a-l-hospita-72327f",
  "el cultiva verdures i fruites.": "el-cultiva-verdures-i-fruite-6d1a49",
  "el arregla les dents.": "el-arregla-les-dents",
  "apaga els incendis i porta un casc:": "apaga-els-incendis-i-porta-u-a43789",
  "cura les persones malaltes a l'hospital:": "cura-les-persones-malaltes-a-9702d5",
  "ensenya a llegir i escriure a l'escola:": "ensenya-a-llegir-i-escriure--5baaca",
  "cuina plats deliciosos al restaurant:": "cuina-plats-deliciosos-al-re-bad874",
  "condueix l'avió pel cel:": "condueix-l-avio-pel-cel-0d46fe",
  "de gran vull ser per curar la gent.": "de-gran-vull-ser-per-curar-l-57a348",
  "de gran vull ser per ensenyar.": "de-gran-vull-ser-per-ensenya-35f25e",
  "de gran vull ser per volar.": "de-gran-vull-ser-per-volar",
  "de gran vull ser per cuinar.": "de-gran-vull-ser-per-cuinar",
  "llegeix i copia els oficis:": "llegeix-i-copia-els-oficis",
  "relaciona cada ofici amb el seu lloc de treball:": "relaciona-cada-ofici-amb-el--ee1966",
  "classifica: treballa dins o fora?": "classifica-treballa-dins-o-f-1dc876",
  "qui és? tria l'ofici correcte:": "qui-es-tria-l-ofici-correcte-89ba4d",
  "què fa cada professional?": "que-fa-cada-professional-b293b1",
  "relaciona cada eina amb el seu ofici:": "relaciona-cada-eina-amb-el-s-7a27a2",
  "endevina quin ofici és:": "endevina-quin-ofici-es-3ee65c",
  "de gran vull ser...": "de-gran-vull-ser",
  "pintor": "pintor",
  "granger": "granger",
  "mestre, escola": "mestre-escola",
  "metge, hospital": "metge-hospital",
  "bomber, parc de bombers": "bomber-parc-de-bombers",
  "cuiner, restaurant": "cuiner-restaurant",
  "pilot, avió": "pilot-avio-5eaa35",
  "estetoscopi, metge": "estetoscopi-metge",
  "extintor, bomber": "extintor-bomber",
  "xeringa, infermer": "xeringa-infermer",
  "paella, cuiner": "paella-cuiner",
  "pissarra, mestre": "pissarra-mestre",
  "tisores, jardiner": "tisores-jardiner",
  "marró": "marro-7ed926",
  "rosa": "rosa",
};
