// Emoji mapping for every Catalan word used in the app
// Used to show visual representations alongside words in task components
// IMPORTANT: Each emoji must visually match the workbook illustration

export const wordEmoji: Record<string, string> = {
  // === LA CLASSE (Classroom) ===
  llapis: "✏️",
  goma: "",          // eraser — no emoji exists, broom was WRONG
  bolígraf: "🖊️",
  retolador: "🖊️",
  llibreta: "📓",
  llibre: "📖",
  carpeta: "🗂️",
  estoig: "✏️",       // pencil case — using pencil as closest visual
  maquineta: "✏️",    // pencil sharpener — using pencil as closest visual
  regle: "📏",
  motxilla: "🎒",
  tisores: "✂️",
  pissarra: "",      // chalkboard — no emoji exists
  guix: "",          // chalk — no emoji exists
  borrador: "",      // board eraser — no emoji exists
  paperera: "🗑️",
  ordinador: "💻",
  taula: "",         // desk — no emoji exists
  cadira: "🪑",
  porta: "🚪",
  finestra: "🪟",

  // === L'ESCOLA (School) ===
  aula: "🏫",
  biblioteca: "📚",
  pati: "🌳",
  menjador: "🍽️",
  gimnàs: "🏋️",
  despatx: "🗄️",
  lavabo: "🚻",
  passadís: "🚪",
  entrada: "🏫",
  escales: "🪜",
  escola: "🏫",
  laboratori: "🔬",
  matemàtiques: "🔢",
  llengües: "📝",
  música: "🎵",
  dibuix: "🎨",
  anglès: "🇬🇧",
  informàtica: "💻",
  "educació física": "⚽",
  ciències: "🔬",
  dilluns: "1️⃣",
  dimarts: "2️⃣",
  dimecres: "3️⃣",
  dijous: "4️⃣",
  divendres: "5️⃣",
  dissabte: "6️⃣",
  diumenge: "7️⃣",

  // === EL COS (Body) ===
  cos: "🧍",
  cap: "🧠",
  ull: "👁️",
  ulls: "👀",
  nas: "👃",
  boca: "👄",
  orella: "👂",
  orelles: "👂👂",
  coll: "🦒",
  braç: "💪",
  braços: "💪💪",
  mà: "✋",
  mans: "🙌",
  dit: "☝️",
  dits: "🖐️",
  cama: "🦵",
  cames: "🦵🦵",
  genoll: "🦵",
  peu: "🦶",
  peus: "🦶🦶",
  boques: "👄",
  cabell: "💇",
  veure: "👁️",
  escoltar: "👂",
  parlar: "🗣️",
  olorar: "👃",
  tocar: "✋",

  // === LA ROBA (Clothing) ===
  anorac: "🧥",
  jersei: "🧶",
  texans: "👖",
  camisa: "👔",
  samarreta: "👕",
  jaqueta: "🧥",
  abric: "🧥",
  sabatilles: "👟",
  pantalons: "👖",
  vestit: "👗",
  faldilla: "👗",
  gorra: "🧢",
  bufanda: "🧣",
  guants: "🧤",
  mitges: "🧦",
  botes: "👢",
  pijama: "🛏️",
  sabates: "👞",
  mitjons: "🧦",
  barret: "🎩",
  xandall: "👟",
  americana: "🧥",
  cinturó: "👔",
  banyador: "🩱",
  biquini: "👙",
  bragues: "👙",
  "samarreta de tirants": "👕",
  calçotets: "🩲",
  calcetes: "🧦",
  arracades: "💎",
  anell: "💍",
  collaret: "📿",
  ulleres: "👓",
  corbata: "👔",
  sandàlies: "👡",
  "pantalons curts": "🩳",
  caputxa: "🧥",

  // === LA CASA (House) ===
  cuina: "🍳",
  habitació: "🛏️",
  bany: "🛁",
  escala: "🪜",
  terrat: "🏠",
  jardí: "🌺",
  balcó: "🏠",
  garatge: "🅿️",
  "sala d'estar": "🛋️",
  casa: "🏠",
  taulada: "🏠",
  "llar de foc": "🔥",
  butaca: "🛋️",
  planta: "🪴",
  aigualera: "🚰",
  escorreplats: "🍽️",
  fogons: "🔥",
  dutxa: "🚿",
  esponja: "🧽",
  sofà: "🛋️",
  llit: "🛏️",
  televisió: "📺",
  mirall: "🪞",
  nevera: "🧊",
  armari: "🗄️",
  coixí: "🛏️",
  cortina: "🪟",
  catifa: "🧶",
  llàmpada: "💡",
  quadre: "🖼️",
  prestatgeria: "📚",
  rellotge: "🕐",
  persiana: "🪟",
  microones: "📻",
  façana: "🏠",
  xemeneia: "🏠",
  antena: "📡",

  // === LA FAMÍLIA (Family) ===
  pare: "👨",
  mare: "👩",
  germà: "👦",
  germana: "👧",
  avi: "👴",
  àvia: "👵",
  oncle: "👨",
  tia: "👩",
  tieta: "👩",
  marit: "👨",
  cosí: "👦",
  cosina: "👧",
  fill: "👦",
  filla: "👧",
  bebè: "👶",
  nebot: "👦",
  neboda: "👧",
  home: "👨",
  dona: "👩",
  noi: "👦",
  noia: "👧",

  // === LES BOTIGUES (Shops) ===
  supermercat: "🛒",
  forn: "🍞",
  fleca: "🍞",
  peixateria: "🐟",
  carnisseria: "🥩",
  farmàcia: "💊",
  llibreria: "📖",
  pastisseria: "🍰",
  fruiteria: "🍎",
  joguineria: "🧸",
  "botiga de roba": "👗",
  sabateria: "👟",
  pa: "🍞",
  peix: "🐟",
  carn: "🥩",
  fruita: "🍎",
  joguines: "🧸",
  medicaments: "💊",
  medicament: "💊",
  tirita: "🩹",
  pastilla: "💊",
  xarop: "🧴",
  termòmetre: "🌡️",
  crema: "🧴",
  mongetes: "🫘",
  préssec: "🍑",
  cireres: "🍒",
  croissant: "🥐",
  "barra de pa": "🥖",

  // === EL MENJAR (Food) ===
  poma: "🍎",
  pera: "🍐",
  plàtan: "🍌",
  taronja: "🍊",
  maduixa: "🍓",
  tomàquet: "🍅",
  pastanaga: "🥕",
  llet: "🥛",
  formatge: "🧀",
  ou: "🥚",
  ceba: "🧅",
  enciam: "🥬",
  patata: "🥔",
  cereals: "🥣",
  sopa: "🍲",
  amanida: "🥗",
  cullera: "🥄",
  forquilla: "🍴",
  ganivet: "🔪",
  got: "🥛",
  esmorzar: "🌅",
  dinar: "☀️",
  berenar: "🌤️",
  sopar: "🌙",
  tassa: "☕",
  ampolla: "🍾",
  copa: "🥂",
  cafè: "☕",
  te: "🍵",
  verdures: "🥬",
  "patates fregides": "🍟",
  macarrons: "🍝",
  sandvitx: "🥪",
  iogurt: "🥛",
  tonyina: "🐟",
  salmó: "🐟",
  calamar: "🦑",
  musclo: "🦪",
  mandonguilles: "🧆",
  bistec: "🥩",
  "pa de motlle": "🍞",
  refresc: "🥤",
  aigua: "💧",

  // === ELS ANIMALS (Animals) ===
  gos: "🐕",
  gat: "🐱",
  conill: "🐰",
  lleó: "🦁",
  tigre: "🐯",
  elefant: "🐘",
  ocell: "🦜",
  tortuga: "🐢",
  serp: "🐍",
  girafa: "🦒",
  dofí: "🐬",
  balena: "🐋",
  hàmster: "🐹",
  gall: "🐓",
  pollet: "🐤",
  mosca: "🪰",
  mosquit: "🦟",
  gorila: "🦍",
  camell: "🐫",
  lince: "🐈",
  guineu: "🦊",
  "peix espasa": "🐟",
  bacallà: "🐟",
  pingüí: "🐧",
  estruç: "🦤",
  gaviota: "🕊️",

  // === LA CIUTAT (City) ===
  carrer: "🛣️",
  plaça: "⛲",
  parc: "🌳",
  hospital: "🏥",
  estació: "🚉",
  museu: "🏛️",
  cinema: "🎬",
  restaurant: "🍽️",
  mercat: "🏪",
  semàfor: "🚦",
  teatre: "🎭",
  ajuntament: "🏛️",
  "pel·lícules": "🎬",

  // === ELS VEHICLES (Vehicles) ===
  cotxe: "🚗",
  autobús: "🚌",
  tren: "🚂",
  avió: "✈️",
  bicicleta: "🚲",
  moto: "🏍️",
  vaixell: "🚢",
  helicòpter: "🚁",
  camió: "🚛",
  taxi: "🚕",
  ambulància: "🚑",
  barca: "⛵",
  metro: "🚇",
  patinet: "🛴",
  tramvia: "🚊",
  carretera: "🛣️",
  mar: "🌊",
  cel: "☁️",
  vies: "🛤️",
  "sota terra": "🕳️",

  // === ELS OFICIS (Professions) ===
  mestre: "👨‍🏫",
  metge: "👨‍⚕️",
  bomber: "🧑‍🚒",
  policia: "👮",
  cuiner: "👨‍🍳",
  infermer: "👩‍⚕️",
  pilot: "👨‍✈️",
  cambrer: "🍽️",
  dentista: "🦷",
  veterinari: "🐾",
  jardiner: "🌱",
  pagès: "👨‍🌾",
  carter: "📮",

  // === Action verbs ===
  escriure: "✍️",
  esborrar: "",     // erasing — broom was WRONG
  tallar: "✂️",
  portar: "🎒",
  dibuixar: "🎨",
};

// Words that have 3D illustration PNGs in /public/illustrations/
// As illustrations are generated, add the word here
const wordsWithIllustrations = new Set([
  "llapis",
  "goma",
  "retolador",
  "regle",
  "tisores",
  "llibre",
  "quadern",
  "motxilla",
  "boligraf",
  "llibreta",
  "carpeta",
  "estoig",
  "maquineta",
  "pissarra",
  "guix",
  "borrador",
  "paperera",
  "ordinador",
  "taula",
  "cadira",
  "porta",
  "finestra",
  // L'escola
  "aula",
  "biblioteca",
  "pati",
  "menjador",
  "gimnas",
  "despatx",
  "lavabo",
  "passadis",
  "entrada",
  "escales",
  "escola",
  // El cos
  "cos",
  "cap",
  "ull",
  "nas",
  "boca",
  "orella",
  "coll",
  "brac",
  "ma",
  "dit",
  "cama",
  "genoll",
  "peu",
  "cabell",
  "veure",
  "escoltar",
  "parlar",
  "olorar",
  "tocar",
  // La roba
  "anorac",
  "jersei",
  "texans",
  "camisa",
  "samarreta",
  "jaqueta",
  "sabatilles",
  "abric",
  "pantalons",
  "vestit",
  "faldilla",
  "gorra",
  "bufanda",
  "guants",
  "mitges",
  "botes",
  "pijama",
  "sabates",
  "mitjons",
  "barret",
  "vambes",
  "xandall",
  "americana",
  "corbata",
  "banyador",
  "banyador-de-dona",
  "biquini",
  "sandalies",
  "arracades",
  "anell",
  "ulleres",
  "collaret",
  "cinturo",
  "caputxa",
  "pantalons-curts",
  "samarreta-de-tirants",
  // La casa
  "cuina",
  "habitacio",
  // "bany", — removed: bad Bing illustration (two bathtubs), lavabo covers bathroom
  "escala",
  "terrat",
  "jardi",
  "balco",
  "garatge",
  "sala-d-estar",
  "casa",
  "taulada",
  "llar-de-foc",
  "butaca",
  "planta",
  "aigualera",
  "escorreplats",
  "fogons",
  "dutxa",
  "esponja",
  "sofa",
  "llit",
  "televisio",
  "mirall",
  "nevera",
  "armari",
  "coixi",
  "cortina",
  "catifa",
  "llampada",
  "quadre",
  "prestatgeria",
  "rellotge",
  "persiana",
  "microones",
  "facana",
  "xemeneia",
  "antena",
  // La família
  "pare",
  "mare",
  "germa",
  "germana",
  "avi",
  "avia",
  "oncle",
  "tieta",
  "cosi",
  "cosina",
  "fill",
  "filla",
  "bebe",
  "nebot",
  "neboda",
  "marit",
  // Les botigues
  "supermercat",
  "fleca",
  "farmacia",
  "pastisseria",
  "fruiteria",
  "joguineria",
  "carnisseria",
  "peixateria",
  "llibreria",
  "sabateria",
  "botiga-de-roba",
  // El menjar
  "poma",
  "pera",
  "platan",
  "taronja",
  "maduixa",
  "tomaquet",
  "pastanaga",
  "llet",
  "formatge",
  "ou",
  "ceba",
  "enciam",
  "patata",
  "cereals",
  "sopa",
  "amanida",
  "cullera",
  "forquilla",
  "ganivet",
  "got",
  "tassa",
  "ampolla",
  "copa",
  "cafe",
  "te",
  "verdures",
  "patates-fregides",
  "macarrons",
  "sandvitx",
  "iogurt",
  "tonyina",
  "salmo",
  "calamar",
  "musclo",
  "mandonguilles",
  "bistec",
  "pa-de-motlle",
  "refresc",
  "aigua",
  "esmorzar",
  "dinar",
  "berenar",
  "sopar",
]);

// Strip accents for filename matching (e.g. "bolígraf" → "boligraf")
function stripAccents(s: string): string {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

// Get the illustration image path for a word (returns null if no illustration exists)
export function getWordIllustration(word: string): string | null {
  const key = stripAccents(word.toLowerCase().trim()).replace(/\s+/g, "-");
  if (wordsWithIllustrations.has(key)) {
    return `/illustrations/${key}.png`;
  }
  return null;
}

// Get emoji for a word (case-insensitive, returns empty string if not found)
export function getWordEmoji(word: string): string {
  const lower = word.toLowerCase().trim();
  return wordEmoji[lower] || "";
}
