// Emoji mapping for every Catalan word used in the app
// Used to show visual representations alongside words in task components

export const wordEmoji: Record<string, string> = {
  // === LA CLASSE (Classroom) ===
  llapis: "✏️",
  goma: "🧹",
  bolígraf: "🖊️",
  retolador: "🖍️",
  llibreta: "📓",
  estoig: "🎒",
  motxilla: "🎒",
  tisores: "✂️",
  cabell: "💇",
  gomes: "🧹",
  bolígrafs: "🖊️",
  estoigs: "🎒",
  "llapis (molts)": "✏️✏️",

  // === L'ESCOLA (School) ===
  aula: "🏫",
  biblioteca: "📚",
  pati: "🌳",
  menjador: "🍽️",
  gimnàs: "🏋️",
  despatx: "🗄️",
  lavabo: "🚿",
  passadís: "🚪",
  entrada: "🚪",
  escales: "🪜",
  escola: "🏫",

  // === EL COS (Body) ===
  cap: "🧠",
  ull: "👁️",
  ulls: "👀",
  nas: "👃",
  boca: "👄",
  orella: "👂",
  orelles: "👂👂",
  coll: "🦒",
  braç: "💪",
  braços: "💪💪",
  mà: "✋",
  mans: "🙌",
  dit: "☝️",
  dits: "🖐️",
  cama: "🦵",
  cames: "🦵🦵",
  genoll: "🦵",
  peu: "🦶",
  peus: "🦶🦶",
  boques: "👄",
  veure: "👁️",
  escoltar: "👂",
  parlar: "🗣️",
  olorar: "👃",
  tocar: "✋",

  // === LA ROBA (Clothing) ===
  vestit: "👗",
  camisa: "👔",
  samarreta: "👕",
  jaqueta: "🧥",
  pantalons: "👖",
  sabates: "👟",
  faldilla: "👗",
  mitjons: "🧦",
  botes: "👢",
  abric: "🧥",
  barret: "🎩",
  bufanda: "🧣",
  guants: "🧤",
  cinturó: "👔",
  pijama: "🛏️",

  // === LA CASA (House) ===
  cuina: "🍳",
  habitació: "🛏️",
  bany: "🛁",
  escala: "🪜",
  terrat: "🏠",
  jardí: "🌺",
  balcó: "🏠",
  garatge: "🅿️",
  "sala d'estar": "🛋️",
  casa: "🏠",

  // === LA FAMÍLIA (Family) ===
  pare: "👨",
  mare: "👩",
  germà: "👦",
  germana: "👧",
  avi: "👴",
  àvia: "👵",
  oncle: "👨",
  tia: "👩",
  cosí: "👦",
  cosina: "👧",
  fill: "👶",
  filla: "👶",
  home: "👨",
  dona: "👩",
  noi: "👦",
  noia: "👧",

  // === LES BOTIGUES (Shops) ===
  supermercat: "🛒",
  forn: "🍞",
  peixateria: "🐟",
  carnisseria: "🥩",
  farmàcia: "💊",
  llibreria: "📖",
  pastisseria: "🍰",
  fruiteria: "🍎",
  sabateria: "👟",
  "botiga de roba": "👗",
  pa: "🍞",
  peix: "🐟",
  carn: "🥩",
  fruita: "🍎",
  medicaments: "💊",
  medicament: "💊",

  // === EL MENJAR (Food) ===
  poma: "🍎",
  pera: "🍐",
  plàtan: "🍌",
  taronja: "🍊",
  maduixa: "🍓",
  tomàquet: "🍅",
  pastanaga: "🥕",
  llet: "🥛",
  formatge: "🧀",
  ou: "🥚",
  ceba: "🧅",
  enciam: "🥬",
  patata: "🥔",
  cereals: "🥣",
  sopa: "🍲",
  amanida: "🥗",
  cullera: "🥄",
  forquilla: "🍴",
  ganivet: "🔪",
  got: "🥛",
  esmorzar: "🌅",
  dinar: "☀️",
  berenar: "🌤️",
  sopar: "🌙",

  // === ELS ANIMALS (Animals) ===
  gos: "🐕",
  gat: "🐱",
  conill: "🐰",
  lleó: "🦁",
  tigre: "🐯",
  elefant: "🐘",
  ocell: "🐦",
  tortuga: "🐢",
  serp: "🐍",
  girafa: "🦒",
  dofí: "🐬",
  balena: "🐋",
  flamenc: "🦩",
  hàmster: "🐹",

  // === LA CIUTAT (City) ===
  carrer: "🛣️",
  plaça: "⛲",
  parc: "🌳",
  hospital: "🏥",
  estació: "🚉",
  museu: "🏛️",
  cinema: "🎬",
  restaurant: "🍽️",
  mercat: "🏪",
  semàfor: "🚦",
  teatre: "🎭",
  ajuntament: "🏛️",
  "pel·lícules": "🎬",

  // === ELS VEHICLES (Vehicles) ===
  cotxe: "🚗",
  autobús: "🚌",
  tren: "🚂",
  avió: "✈️",
  bicicleta: "🚲",
  moto: "🏍️",
  vaixell: "🚢",
  helicòpter: "🚁",
  camió: "🚛",
  taxi: "🚕",
  ambulància: "🚑",
  barca: "⛵",
  metro: "🚇",
  patinet: "🛴",
  tramvia: "🚊",
  carretera: "🛣️",
  mar: "🌊",
  cel: "☁️",
  vies: "🛤️",
  "sota terra": "🕳️",

  // === ELS OFICIS (Professions) ===
  mestre: "👨‍🏫",
  metge: "👨‍⚕️",
  bomber: "🧑‍🚒",
  policia: "👮",
  cuiner: "👨‍🍳",
  infermer: "👩‍⚕️",
  pilot: "👨‍✈️",
  cambrer: "🍽️",
  dentista: "🦷",
  veterinari: "🐾",
  jardiner: "🌱",
  pagès: "👨‍🌾",
  carter: "📮",

  // === Action verbs ===
  escriure: "✍️",
  esborrar: "🧹",
  tallar: "✂️",
  portar: "🎒",
  dibuixar: "🎨",
};

// Get emoji for a word (case-insensitive, returns empty string if not found)
export function getWordEmoji(word: string): string {
  const lower = word.toLowerCase().trim();
  return wordEmoji[lower] || "";
}
