import type { StarExpression } from "./starTypes";

export interface ExpressionData {
  // Eyes
  eyeScaleX: number;
  eyeScaleY: number;
  pupilRadius: number;
  pupilOffsetX: number;
  pupilOffsetY: number;
  pupilType: "circle" | "heart" | "x" | "spiral" | "star";
  eyelidClose: number; // 0 = open, 1 = fully closed

  // Eyebrows
  browOffsetY: number;
  browRotation: number; // degrees, positive = inner raised
  browCurve: number; // 0 = flat, positive = arched up

  // Mouth path (all use same structure for crossfade)
  mouthPath: string;
  mouthScale: number;

  // Cheeks
  cheekOpacity: number;

  // Extras
  showTongue: boolean;
  showSweat: boolean;
}

// Mouth paths centered around (0, 0), approx width 20
const MOUTH = {
  smile: "M -8,0 Q -4,6 0,7 Q 4,6 8,0",
  bigGrin: "M -10,0 Q -5,9 0,10 Q 5,9 10,0",
  oShape: "M -5,-4 Q -5,4 0,5 Q 5,4 5,-4 Q 5,-6 0,-6 Q -5,-6 -5,-4 Z",
  wavy: "M -8,0 Q -4,4 0,0 Q 4,-4 8,0",
  flat: "M -7,0 L 7,0",
  frown: "M -7,4 Q -3,-2 0,-3 Q 3,-2 7,4",
  gentleSmile: "M -6,0 Q -3,4 0,5 Q 3,4 6,0",
  wideSmile: "M -9,0 Q -4,8 0,9 Q 4,8 9,0",
  tongueOut: "M -8,0 Q -4,6 0,7 Q 4,6 8,0",
  tinySmile: "M -4,0 Q -2,3 0,3 Q 2,3 4,0",
  worried: "M -6,2 Q -3,-1 0,0 Q 3,-1 6,2",
};

export const expressionData: Record<StarExpression, ExpressionData> = {
  happy: {
    eyeScaleX: 1,
    eyeScaleY: 1,
    pupilRadius: 3,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "circle",
    eyelidClose: 0,
    browOffsetY: 0,
    browRotation: 0,
    browCurve: 2,
    mouthPath: MOUTH.smile,
    mouthScale: 1,
    cheekOpacity: 0.3,
    showTongue: false,
    showSweat: false,
  },
  excited: {
    eyeScaleX: 1.2,
    eyeScaleY: 1.3,
    pupilRadius: 2.5,
    pupilOffsetX: 0,
    pupilOffsetY: -0.5,
    pupilType: "circle",
    eyelidClose: 0,
    browOffsetY: -3,
    browRotation: 0,
    browCurve: 4,
    mouthPath: MOUTH.bigGrin,
    mouthScale: 1,
    cheekOpacity: 0.6,
    showTongue: false,
    showSweat: false,
  },
  celebrating: {
    eyeScaleX: 1.1,
    eyeScaleY: 0.5,
    pupilRadius: 2.5,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "star",
    eyelidClose: 0.4,
    browOffsetY: -3,
    browRotation: 0,
    browCurve: 5,
    mouthPath: MOUTH.wideSmile,
    mouthScale: 1.1,
    cheekOpacity: 0.7,
    showTongue: false,
    showSweat: false,
  },
  confused: {
    eyeScaleX: 1,
    eyeScaleY: 1.1,
    pupilRadius: 3,
    pupilOffsetX: 2,
    pupilOffsetY: -1,
    pupilType: "circle",
    eyelidClose: 0,
    browOffsetY: -1,
    browRotation: 12,
    browCurve: 0,
    mouthPath: MOUTH.wavy,
    mouthScale: 1,
    cheekOpacity: 0,
    showTongue: false,
    showSweat: false,
  },
  sad: {
    eyeScaleX: 0.9,
    eyeScaleY: 0.8,
    pupilRadius: 3.5,
    pupilOffsetX: 0,
    pupilOffsetY: 2,
    pupilType: "circle",
    eyelidClose: 0.3,
    browOffsetY: 0,
    browRotation: -10,
    browCurve: -2,
    mouthPath: MOUTH.frown,
    mouthScale: 0.9,
    cheekOpacity: 0,
    showTongue: false,
    showSweat: false,
  },
  shocked: {
    eyeScaleX: 1.4,
    eyeScaleY: 1.5,
    pupilRadius: 2,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "circle",
    eyelidClose: 0,
    browOffsetY: -5,
    browRotation: 0,
    browCurve: 6,
    mouthPath: MOUTH.oShape,
    mouthScale: 1,
    cheekOpacity: 0,
    showTongue: false,
    showSweat: false,
  },
  dizzy: {
    eyeScaleX: 1.1,
    eyeScaleY: 1.1,
    pupilRadius: 3,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "spiral",
    eyelidClose: 0,
    browOffsetY: -1,
    browRotation: 5,
    browCurve: 0,
    mouthPath: MOUTH.wavy,
    mouthScale: 0.9,
    cheekOpacity: 0.2,
    showTongue: false,
    showSweat: true,
  },
  loving: {
    eyeScaleX: 1,
    eyeScaleY: 1,
    pupilRadius: 3.5,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "heart",
    eyelidClose: 0,
    browOffsetY: -1,
    browRotation: 0,
    browCurve: 3,
    mouthPath: MOUTH.gentleSmile,
    mouthScale: 1,
    cheekOpacity: 0.6,
    showTongue: false,
    showSweat: false,
  },
  smart: {
    eyeScaleX: 0.9,
    eyeScaleY: 0.85,
    pupilRadius: 3,
    pupilOffsetX: 1,
    pupilOffsetY: -1,
    pupilType: "circle",
    eyelidClose: 0.2,
    browOffsetY: -2,
    browRotation: 3,
    browCurve: 2,
    mouthPath: MOUTH.tinySmile,
    mouthScale: 1,
    cheekOpacity: 0,
    showTongue: false,
    showSweat: false,
  },
  sleeping: {
    eyeScaleX: 1,
    eyeScaleY: 0.15,
    pupilRadius: 0,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "circle",
    eyelidClose: 1,
    browOffsetY: 2,
    browRotation: 0,
    browCurve: -1,
    mouthPath: MOUTH.flat,
    mouthScale: 0.7,
    cheekOpacity: 0.4,
    showTongue: false,
    showSweat: false,
  },
  laughing: {
    eyeScaleX: 1.1,
    eyeScaleY: 0.3,
    pupilRadius: 0,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "circle",
    eyelidClose: 0.8,
    browOffsetY: -3,
    browRotation: 0,
    browCurve: 4,
    mouthPath: MOUTH.bigGrin,
    mouthScale: 1.1,
    cheekOpacity: 0.5,
    showTongue: false,
    showSweat: false,
  },
  fainted: {
    eyeScaleX: 1,
    eyeScaleY: 1,
    pupilRadius: 4,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "x",
    eyelidClose: 0,
    browOffsetY: 2,
    browRotation: -5,
    browCurve: -2,
    mouthPath: MOUTH.tongueOut,
    mouthScale: 0.8,
    cheekOpacity: 0,
    showTongue: true,
    showSweat: false,
  },
  nervous: {
    eyeScaleX: 1,
    eyeScaleY: 1.15,
    pupilRadius: 2.5,
    pupilOffsetX: -1,
    pupilOffsetY: -1,
    pupilType: "circle",
    eyelidClose: 0,
    browOffsetY: -2,
    browRotation: -8,
    browCurve: 1,
    mouthPath: MOUTH.worried,
    mouthScale: 0.9,
    cheekOpacity: 0.2,
    showTongue: false,
    showSweat: true,
  },
  proud: {
    eyeScaleX: 0.95,
    eyeScaleY: 0.7,
    pupilRadius: 3,
    pupilOffsetX: 0,
    pupilOffsetY: 0,
    pupilType: "circle",
    eyelidClose: 0.3,
    browOffsetY: -2,
    browRotation: 2,
    browCurve: 3,
    mouthPath: MOUTH.smile,
    mouthScale: 1.1,
    cheekOpacity: 0.4,
    showTongue: false,
    showSweat: false,
  },
};
